// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2/1130128 Production Release
//  HLS Date:       Mon Aug 26 21:59:12 PDT 2024
// 
//  Generated by:   zsm9@zhang-21.ece.cornell.edu
//  Generated date: Thu Jul 30 17:36:14 2026
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    pe_wire_comb
// ------------------------------------------------------------------


module pe_wire_comb (
  done, u0_done, u1_done, u2_done, u3_done
);
  output done;
  input u0_done;
  input u1_done;
  input u2_done;
  input u3_done;



  // Interconnect Declarations for Component Instantiations 
  assign done = u3_done & u1_done & u0_done & u2_done;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    AlloFifo_ac_int_32_true_2_deq_thread_deq_thread_fsm
//  FSM Module
// ------------------------------------------------------------------


module AlloFifo_ac_int_32_true_2_deq_thread_deq_thread_fsm (
  clk, rst, fsm_output
);
  input clk;
  input rst;
  output [1:0] fsm_output;
  reg [1:0] fsm_output;


  // FSM State Type Declaration for AlloFifo_ac_int_32_true_2_deq_thread_deq_thread_fsm_1
  parameter
    while_C_0 = 1'd0,
    while_C_1 = 1'd1;

  reg  state_var;
  reg  state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : AlloFifo_ac_int_32_true_2_deq_thread_deq_thread_fsm_1
    case (state_var)
      while_C_1 : begin
        fsm_output = 2'b10;
        state_var_NS = while_C_0;
      end
      // while_C_0
      default : begin
        fsm_output = 2'b01;
        state_var_NS = while_C_1;
      end
    endcase
  end

  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      state_var <= while_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    AlloFifo_ac_int_32_true_2_enq_thread_enq_thread_fsm
//  FSM Module
// ------------------------------------------------------------------


module AlloFifo_ac_int_32_true_2_enq_thread_enq_thread_fsm (
  clk, rst, fsm_output
);
  input clk;
  input rst;
  output [1:0] fsm_output;
  reg [1:0] fsm_output;


  // FSM State Type Declaration for AlloFifo_ac_int_32_true_2_enq_thread_enq_thread_fsm_1
  parameter
    while_C_0 = 1'd0,
    while_C_1 = 1'd1;

  reg  state_var;
  reg  state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : AlloFifo_ac_int_32_true_2_enq_thread_enq_thread_fsm_1
    case (state_var)
      while_C_1 : begin
        fsm_output = 2'b10;
        state_var_NS = while_C_0;
      end
      // while_C_0
      default : begin
        fsm_output = 2'b01;
        state_var_NS = while_C_1;
      end
    endcase
  end

  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      state_var <= while_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    feed_0_run_run_fsm
//  FSM Module
// ------------------------------------------------------------------


module feed_0_run_run_fsm (
  clk, rst, fsm_output, to_sc_37_for_C_0_tr0, v0_req_Push_1_do_C_1_tr0, v0_rsp_Pop_1_do_C_0_tr0,
      v1_Push_1_do_C_0_tr0, to_sc_37_1_for_C_0_tr0, v0_req_Push_3_do_C_1_tr0, v0_rsp_Pop_3_do_C_0_tr0,
      v2_Push_1_do_C_0_tr0, v2_Push_1_do_C_0_tr1
);
  input clk;
  input rst;
  output [11:0] fsm_output;
  reg [11:0] fsm_output;
  input to_sc_37_for_C_0_tr0;
  input v0_req_Push_1_do_C_1_tr0;
  input v0_rsp_Pop_1_do_C_0_tr0;
  input v1_Push_1_do_C_0_tr0;
  input to_sc_37_1_for_C_0_tr0;
  input v0_req_Push_3_do_C_1_tr0;
  input v0_rsp_Pop_3_do_C_0_tr0;
  input v2_Push_1_do_C_0_tr0;
  input v2_Push_1_do_C_0_tr1;


  // FSM State Type Declaration for feed_0_run_run_fsm_1
  parameter
    run_rlp_C_0 = 4'd0,
    to_sc_37_for_C_0 = 4'd1,
    v0_req_Push_1_do_C_0 = 4'd2,
    v0_req_Push_1_do_C_1 = 4'd3,
    v0_rsp_Pop_1_do_C_0 = 4'd4,
    v1_Push_1_do_C_0 = 4'd5,
    to_sc_37_1_for_C_0 = 4'd6,
    v0_req_Push_3_do_C_0 = 4'd7,
    v0_req_Push_3_do_C_1 = 4'd8,
    v0_rsp_Pop_3_do_C_0 = 4'd9,
    v2_Push_1_do_C_0 = 4'd10,
    while_C_0 = 4'd11;

  reg [3:0] state_var;
  reg [3:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : feed_0_run_run_fsm_1
    case (state_var)
      to_sc_37_for_C_0 : begin
        fsm_output = 12'b000000000010;
        if ( to_sc_37_for_C_0_tr0 ) begin
          state_var_NS = to_sc_37_for_C_0;
        end
        else begin
          state_var_NS = v0_req_Push_1_do_C_0;
        end
      end
      v0_req_Push_1_do_C_0 : begin
        fsm_output = 12'b000000000100;
        state_var_NS = v0_req_Push_1_do_C_1;
      end
      v0_req_Push_1_do_C_1 : begin
        fsm_output = 12'b000000001000;
        if ( v0_req_Push_1_do_C_1_tr0 ) begin
          state_var_NS = to_sc_37_for_C_0;
        end
        else begin
          state_var_NS = v0_rsp_Pop_1_do_C_0;
        end
      end
      v0_rsp_Pop_1_do_C_0 : begin
        fsm_output = 12'b000000010000;
        if ( v0_rsp_Pop_1_do_C_0_tr0 ) begin
          state_var_NS = v1_Push_1_do_C_0;
        end
        else begin
          state_var_NS = v0_rsp_Pop_1_do_C_0;
        end
      end
      v1_Push_1_do_C_0 : begin
        fsm_output = 12'b000000100000;
        if ( v1_Push_1_do_C_0_tr0 ) begin
          state_var_NS = to_sc_37_1_for_C_0;
        end
        else begin
          state_var_NS = v1_Push_1_do_C_0;
        end
      end
      to_sc_37_1_for_C_0 : begin
        fsm_output = 12'b000001000000;
        if ( to_sc_37_1_for_C_0_tr0 ) begin
          state_var_NS = v0_req_Push_3_do_C_0;
        end
        else begin
          state_var_NS = to_sc_37_1_for_C_0;
        end
      end
      v0_req_Push_3_do_C_0 : begin
        fsm_output = 12'b000010000000;
        state_var_NS = v0_req_Push_3_do_C_1;
      end
      v0_req_Push_3_do_C_1 : begin
        fsm_output = 12'b000100000000;
        if ( v0_req_Push_3_do_C_1_tr0 ) begin
          state_var_NS = v0_rsp_Pop_3_do_C_0;
        end
        else begin
          state_var_NS = to_sc_37_1_for_C_0;
        end
      end
      v0_rsp_Pop_3_do_C_0 : begin
        fsm_output = 12'b001000000000;
        if ( v0_rsp_Pop_3_do_C_0_tr0 ) begin
          state_var_NS = v2_Push_1_do_C_0;
        end
        else begin
          state_var_NS = v0_rsp_Pop_3_do_C_0;
        end
      end
      v2_Push_1_do_C_0 : begin
        fsm_output = 12'b010000000000;
        if ( v2_Push_1_do_C_0_tr0 ) begin
          state_var_NS = to_sc_37_for_C_0;
        end
        else if ( v2_Push_1_do_C_0_tr1 ) begin
          state_var_NS = v2_Push_1_do_C_0;
        end
        else begin
          state_var_NS = while_C_0;
        end
      end
      while_C_0 : begin
        fsm_output = 12'b100000000000;
        state_var_NS = while_C_0;
      end
      // run_rlp_C_0
      default : begin
        fsm_output = 12'b000000000001;
        state_var_NS = to_sc_37_for_C_0;
      end
    endcase
  end

  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      state_var <= run_rlp_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    mul_0_run_run_fsm
//  FSM Module
// ------------------------------------------------------------------


module mul_0_run_run_fsm (
  clk, rst, fsm_output, v6_Pop_1_do_C_0_tr0, v7_Pop_1_do_C_0_tr0, v7_Pop_1_do_C_0_tr1
);
  input clk;
  input rst;
  output [3:0] fsm_output;
  reg [3:0] fsm_output;
  input v6_Pop_1_do_C_0_tr0;
  input v7_Pop_1_do_C_0_tr0;
  input v7_Pop_1_do_C_0_tr1;


  // FSM State Type Declaration for mul_0_run_run_fsm_1
  parameter
    run_rlp_C_0 = 2'd0,
    v6_Pop_1_do_C_0 = 2'd1,
    v7_Pop_1_do_C_0 = 2'd2,
    while_C_0 = 2'd3;

  reg [1:0] state_var;
  reg [1:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : mul_0_run_run_fsm_1
    case (state_var)
      v6_Pop_1_do_C_0 : begin
        fsm_output = 4'b0010;
        if ( v6_Pop_1_do_C_0_tr0 ) begin
          state_var_NS = v6_Pop_1_do_C_0;
        end
        else begin
          state_var_NS = v7_Pop_1_do_C_0;
        end
      end
      v7_Pop_1_do_C_0 : begin
        fsm_output = 4'b0100;
        if ( v7_Pop_1_do_C_0_tr0 ) begin
          state_var_NS = v6_Pop_1_do_C_0;
        end
        else if ( v7_Pop_1_do_C_0_tr1 ) begin
          state_var_NS = v7_Pop_1_do_C_0;
        end
        else begin
          state_var_NS = while_C_0;
        end
      end
      while_C_0 : begin
        fsm_output = 4'b1000;
        state_var_NS = while_C_0;
      end
      // run_rlp_C_0
      default : begin
        fsm_output = 4'b0001;
        state_var_NS = v6_Pop_1_do_C_0;
      end
    endcase
  end

  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      state_var <= run_rlp_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    acc_0_run_run_fsm
//  FSM Module
// ------------------------------------------------------------------


module acc_0_run_run_fsm (
  clk, rst, fsm_output, v23_Push_1_do_C_0_tr0, v23_Push_1_do_C_0_tr1
);
  input clk;
  input rst;
  output [3:0] fsm_output;
  reg [3:0] fsm_output;
  input v23_Push_1_do_C_0_tr0;
  input v23_Push_1_do_C_0_tr1;


  // FSM State Type Declaration for acc_0_run_run_fsm_1
  parameter
    run_rlp_C_0 = 2'd0,
    v23_Push_1_do_C_0 = 2'd1,
    l_S_i_0_i2_C_0 = 2'd2,
    while_C_0 = 2'd3;

  reg [1:0] state_var;
  reg [1:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : acc_0_run_run_fsm_1
    case (state_var)
      v23_Push_1_do_C_0 : begin
        fsm_output = 4'b0010;
        if ( v23_Push_1_do_C_0_tr0 ) begin
          state_var_NS = v23_Push_1_do_C_0;
        end
        else if ( v23_Push_1_do_C_0_tr1 ) begin
          state_var_NS = l_S_i_0_i2_C_0;
        end
        else begin
          state_var_NS = while_C_0;
        end
      end
      l_S_i_0_i2_C_0 : begin
        fsm_output = 4'b0100;
        state_var_NS = v23_Push_1_do_C_0;
      end
      while_C_0 : begin
        fsm_output = 4'b1000;
        state_var_NS = while_C_0;
      end
      // run_rlp_C_0
      default : begin
        fsm_output = 4'b0001;
        state_var_NS = v23_Push_1_do_C_0;
      end
    endcase
  end

  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      state_var <= run_rlp_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    sink_0_run_run_fsm
//  FSM Module
// ------------------------------------------------------------------


module sink_0_run_run_fsm (
  clk, rst, fsm_output, v36_Pop_1_do_C_0_tr0, v35_Push_1_do_C_0_tr0, v35_Push_1_do_C_0_tr1
);
  input clk;
  input rst;
  output [3:0] fsm_output;
  reg [3:0] fsm_output;
  input v36_Pop_1_do_C_0_tr0;
  input v35_Push_1_do_C_0_tr0;
  input v35_Push_1_do_C_0_tr1;


  // FSM State Type Declaration for sink_0_run_run_fsm_1
  parameter
    run_rlp_C_0 = 2'd0,
    v36_Pop_1_do_C_0 = 2'd1,
    v35_Push_1_do_C_0 = 2'd2,
    while_C_0 = 2'd3;

  reg [1:0] state_var;
  reg [1:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : sink_0_run_run_fsm_1
    case (state_var)
      v36_Pop_1_do_C_0 : begin
        fsm_output = 4'b0010;
        if ( v36_Pop_1_do_C_0_tr0 ) begin
          state_var_NS = v36_Pop_1_do_C_0;
        end
        else begin
          state_var_NS = v35_Push_1_do_C_0;
        end
      end
      v35_Push_1_do_C_0 : begin
        fsm_output = 4'b0100;
        if ( v35_Push_1_do_C_0_tr0 ) begin
          state_var_NS = v36_Pop_1_do_C_0;
        end
        else if ( v35_Push_1_do_C_0_tr1 ) begin
          state_var_NS = v35_Push_1_do_C_0;
        end
        else begin
          state_var_NS = while_C_0;
        end
      end
      while_C_0 : begin
        fsm_output = 4'b1000;
        state_var_NS = while_C_0;
      end
      // run_rlp_C_0
      default : begin
        fsm_output = 4'b0001;
        state_var_NS = v36_Pop_1_do_C_0;
      end
    endcase
  end

  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      state_var <= run_rlp_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    AlloMem_ac_int_32_true_16_4_32_run_run_fsm
//  FSM Module
// ------------------------------------------------------------------


module AlloMem_ac_int_32_true_16_4_32_run_run_fsm (
  clk, rst, fsm_output, req_Pop_1_do_C_0_tr0, to_ac_37_for_C_0_tr0, to_ac_37_for_C_0_tr1,
      rsp_Push_1_do_C_1_tr0
);
  input clk;
  input rst;
  output [5:0] fsm_output;
  reg [5:0] fsm_output;
  input req_Pop_1_do_C_0_tr0;
  input to_ac_37_for_C_0_tr0;
  input to_ac_37_for_C_0_tr1;
  input rsp_Push_1_do_C_1_tr0;


  // FSM State Type Declaration for AlloMem_ac_int_32_true_16_4_32_run_run_fsm_1
  parameter
    while_C_0 = 3'd0,
    req_Pop_1_do_C_0 = 3'd1,
    to_ac_37_for_C_0 = 3'd2,
    rsp_Push_1_do_C_0 = 3'd3,
    rsp_Push_1_do_C_1 = 3'd4,
    while_C_1 = 3'd5;

  reg [2:0] state_var;
  reg [2:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : AlloMem_ac_int_32_true_16_4_32_run_run_fsm_1
    case (state_var)
      req_Pop_1_do_C_0 : begin
        fsm_output = 6'b000010;
        if ( req_Pop_1_do_C_0_tr0 ) begin
          state_var_NS = to_ac_37_for_C_0;
        end
        else begin
          state_var_NS = req_Pop_1_do_C_0;
        end
      end
      to_ac_37_for_C_0 : begin
        fsm_output = 6'b000100;
        if ( to_ac_37_for_C_0_tr0 ) begin
          state_var_NS = while_C_1;
        end
        else if ( to_ac_37_for_C_0_tr1 ) begin
          state_var_NS = rsp_Push_1_do_C_0;
        end
        else begin
          state_var_NS = to_ac_37_for_C_0;
        end
      end
      rsp_Push_1_do_C_0 : begin
        fsm_output = 6'b001000;
        state_var_NS = rsp_Push_1_do_C_1;
      end
      rsp_Push_1_do_C_1 : begin
        fsm_output = 6'b010000;
        if ( rsp_Push_1_do_C_1_tr0 ) begin
          state_var_NS = while_C_1;
        end
        else begin
          state_var_NS = rsp_Push_1_do_C_0;
        end
      end
      while_C_1 : begin
        fsm_output = 6'b100000;
        state_var_NS = while_C_0;
      end
      // while_C_0
      default : begin
        fsm_output = 6'b000001;
        state_var_NS = req_Pop_1_do_C_0;
      end
    endcase
  end

  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      state_var <= while_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    AlloFifo_ac_int_32_true_2_deq_thread
// ------------------------------------------------------------------


module AlloFifo_ac_int_32_true_2_deq_thread (
  clk, rst, out_vld, out_rdy, out_dat, buf_0, buf_1, buf_2, head_s, tail_s
);
  input clk;
  input rst;
  output out_vld;
  reg out_vld;
  input out_rdy;
  output [31:0] out_dat;
  reg [31:0] out_dat;
  input [31:0] buf_0;
  input [31:0] buf_1;
  input [31:0] buf_2;
  output [1:0] head_s;
  input [31:0] tail_s;


  // Interconnect Declarations
  wire [1:0] fsm_output;
  wire while_while_if_while_empty_while_empty_while_empty_unequal_tmp;
  wire or_tmp_2;
  wire or_tmp_4;
  wire while_if_if_while_if_if_nor_cse;
  reg h_1_0_sva_1;
  reg h_1_0_sva_0;
  reg while_while_if_while_empty_while_empty_while_empty_unequal_svs;


  // Interconnect Declarations for Component Instantiations 
  AlloFifo_ac_int_32_true_2_deq_thread_deq_thread_fsm AlloFifo_ac_int_32_true_2_deq_thread_deq_thread_fsm_inst
      (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output)
    );
  assign head_s = {h_1_0_sva_1 , h_1_0_sva_0};
  assign while_if_if_while_if_if_nor_cse = ~(h_1_0_sva_1 | h_1_0_sva_0);
  assign while_while_if_while_empty_while_empty_while_empty_unequal_tmp = ({h_1_0_sva_1
      , h_1_0_sva_0}) != (tail_s[1:0]);
  assign or_tmp_2 = while_while_if_while_empty_while_empty_while_empty_unequal_svs
      & (fsm_output[1]);
  assign or_tmp_4 = (~(while_while_if_while_empty_while_empty_while_empty_unequal_svs
      & out_rdy)) | (fsm_output[0]);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      out_dat <= 32'b00000000000000000000000000000000;
    end
    else if ( ~((fsm_output[1]) | (~ while_while_if_while_empty_while_empty_while_empty_unequal_tmp))
        ) begin
      out_dat <= MUX1HOT_v_32_3_2(buf_0, buf_1, buf_2, {while_if_if_while_if_if_nor_cse
          , h_1_0_sva_0 , h_1_0_sva_1});
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      out_vld <= 1'b0;
    end
    else if ( (while_while_if_while_empty_while_empty_while_empty_unequal_tmp & (fsm_output[0]))
        | or_tmp_2 ) begin
      out_vld <= ~ or_tmp_2;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      h_1_0_sva_1 <= 1'b0;
    end
    else if ( ~ or_tmp_4 ) begin
      h_1_0_sva_1 <= h_1_0_sva_0;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      h_1_0_sva_0 <= 1'b0;
    end
    else if ( ~ or_tmp_4 ) begin
      h_1_0_sva_0 <= while_if_if_while_if_if_nor_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      while_while_if_while_empty_while_empty_while_empty_unequal_svs <= 1'b0;
    end
    else begin
      while_while_if_while_empty_while_empty_while_empty_unequal_svs <= while_while_if_while_empty_while_empty_while_empty_unequal_tmp;
    end
  end

  function automatic [31:0] MUX1HOT_v_32_3_2;
    input [31:0] input_2;
    input [31:0] input_1;
    input [31:0] input_0;
    input [2:0] sel;
    reg [31:0] result;
  begin
    result = input_0 & {32{sel[0]}};
    result = result | (input_1 & {32{sel[1]}});
    result = result | (input_2 & {32{sel[2]}});
    MUX1HOT_v_32_3_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    AlloFifo_ac_int_32_true_2_enq_thread
// ------------------------------------------------------------------


module AlloFifo_ac_int_32_true_2_enq_thread (
  clk, rst, in_vld, in_rdy, in_dat, buf_0, buf_1, buf_2, head_s, tail_s
);
  input clk;
  input rst;
  input in_vld;
  output in_rdy;
  reg in_rdy;
  input [31:0] in_dat;
  output [31:0] buf_0;
  reg [31:0] buf_0;
  output [31:0] buf_1;
  reg [31:0] buf_1;
  output [31:0] buf_2;
  reg [31:0] buf_2;
  input [31:0] head_s;
  output [1:0] tail_s;


  // Interconnect Declarations
  reg tail_s_pconst_1;
  reg tail_s_pconst_0;
  wire [1:0] fsm_output;
  wire while_while_if_while_full_while_full_while_full_while_full_unequal_tmp;
  wire AlloFifo_ac_int_32_true_2_ModIncr_AlloFifo_ac_int_32_true_2_ModIncr_AlloFifo_ac_int_32_true_2_ModIncr_nor_tmp;
  wire or_dcpl_1;
  wire or_tmp_1;
  wire or_tmp_6;
  reg while_while_if_while_full_while_full_while_full_while_full_unequal_svs;
  reg AlloFifo_ac_int_32_true_2_ModIncr_qr_1_0_lpi_1_dfm_0;


  // Interconnect Declarations for Component Instantiations 
  AlloFifo_ac_int_32_true_2_enq_thread_enq_thread_fsm AlloFifo_ac_int_32_true_2_enq_thread_enq_thread_fsm_inst
      (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output)
    );
  assign tail_s = {tail_s_pconst_1 , tail_s_pconst_0};
  assign AlloFifo_ac_int_32_true_2_ModIncr_AlloFifo_ac_int_32_true_2_ModIncr_AlloFifo_ac_int_32_true_2_ModIncr_nor_tmp
      = ~(tail_s_pconst_0 | tail_s_pconst_1);
  assign while_while_if_while_full_while_full_while_full_while_full_unequal_tmp =
      ({tail_s_pconst_0 , AlloFifo_ac_int_32_true_2_ModIncr_AlloFifo_ac_int_32_true_2_ModIncr_AlloFifo_ac_int_32_true_2_ModIncr_nor_tmp})
      != (head_s[1:0]);
  assign or_dcpl_1 = ~(while_while_if_while_full_while_full_while_full_while_full_unequal_svs
      & in_vld);
  assign or_tmp_1 = while_while_if_while_full_while_full_while_full_while_full_unequal_svs
      & (fsm_output[1]);
  assign or_tmp_6 = or_dcpl_1 | (fsm_output[0]);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      in_rdy <= 1'b0;
    end
    else if ( (while_while_if_while_full_while_full_while_full_while_full_unequal_tmp
        & (fsm_output[0])) | or_tmp_1 ) begin
      in_rdy <= ~ or_tmp_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      buf_0 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~(or_dcpl_1 | tail_s_pconst_0 | tail_s_pconst_1 | (fsm_output[0]))
        ) begin
      buf_0 <= in_dat;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      buf_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~(or_dcpl_1 | (~ tail_s_pconst_0) | tail_s_pconst_1 | (fsm_output[0]))
        ) begin
      buf_1 <= in_dat;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      buf_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~(or_dcpl_1 | tail_s_pconst_0 | (~ tail_s_pconst_1) | (fsm_output[0]))
        ) begin
      buf_2 <= in_dat;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      tail_s_pconst_1 <= 1'b0;
    end
    else if ( ~ or_tmp_6 ) begin
      tail_s_pconst_1 <= tail_s_pconst_0;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      tail_s_pconst_0 <= 1'b0;
    end
    else if ( ~ or_tmp_6 ) begin
      tail_s_pconst_0 <= AlloFifo_ac_int_32_true_2_ModIncr_qr_1_0_lpi_1_dfm_0;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      AlloFifo_ac_int_32_true_2_ModIncr_qr_1_0_lpi_1_dfm_0 <= 1'b0;
    end
    else if ( while_while_if_while_full_while_full_while_full_while_full_unequal_tmp
        ) begin
      AlloFifo_ac_int_32_true_2_ModIncr_qr_1_0_lpi_1_dfm_0 <= AlloFifo_ac_int_32_true_2_ModIncr_AlloFifo_ac_int_32_true_2_ModIncr_AlloFifo_ac_int_32_true_2_ModIncr_nor_tmp;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      while_while_if_while_full_while_full_while_full_while_full_unequal_svs <= 1'b0;
    end
    else begin
      while_while_if_while_full_while_full_while_full_while_full_unequal_svs <= while_while_if_while_full_while_full_while_full_while_full_unequal_tmp;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    feed_0_run
// ------------------------------------------------------------------


module feed_0_run (
  clk, rst, done, v0_req_vld, v0_req_rdy, v0_req_dat, v0_rsp_vld, v0_rsp_rdy, v0_rsp_dat,
      v1_vld, v1_rdy, v1_dat, v2_vld, v2_rdy, v2_dat
);
  input clk;
  input rst;
  output done;
  reg done;
  output v0_req_vld;
  reg v0_req_vld;
  input v0_req_rdy;
  output [36:0] v0_req_dat;
  input v0_rsp_vld;
  output v0_rsp_rdy;
  reg v0_rsp_rdy;
  input [31:0] v0_rsp_dat;
  output v1_vld;
  reg v1_vld;
  input v1_rdy;
  output [31:0] v1_dat;
  reg [31:0] v1_dat;
  output v2_vld;
  reg v2_vld;
  input v2_rdy;
  output [31:0] v2_dat;
  reg [31:0] v2_dat;


  // Interconnect Declarations
  wire [11:0] fsm_output;
  wire [3:0] l_S_i_0_i_acc_3_tmp;
  wire [4:0] nl_l_S_i_0_i_acc_3_tmp;
  wire and_dcpl_4;
  wire or_dcpl_8;
  wire or_dcpl_9;
  wire and_46_cse;
  wire and_51_cse;
  reg to_sc_37_1_for_i_1_0_sva_0;
  wire v0_req_dat_or_ssc;
  reg reg_v0_req_dat_ftd;
  reg [3:0] reg_v0_req_dat_ftd_1;
  reg reg_v0_req_dat_ftd_2;
  reg [3:0] reg_v0_req_dat_ftd_3;
  reg reg_to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_1_ftd;
  reg [3:0] reg_to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_1_ftd_1;
  wire nand_4_cse;
  wire v2_dat_and_cse;
  wire reg_l_S_i_0_i_i_3_0_sva_2_l_S_i_0_i_i_l_S_i_0_i_i_and_cse;
  wire v1_dat_and_cse;
  wire [4:0] z_out;
  reg [3:0] to_sc_37_for_to_sc_37_for_rshift_3_0_sva;
  reg [2:0] l_S_i_0_i_i_3_0_sva_2_0;
  wire v0_rsp_rdy_mx0c1;
  wire to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_mx0c1;
  wire to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_sva_mx0c2;
  wire to_sc_37_1_for_i_1_0_sva_0_mx0c1;
  wire to_sc_37_1_for_or_ssc;
  reg to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_4;
  reg [3:0] to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_3_0;
  wire mux_tmp;

  wire[3:0] to_sc_37_for_and_nl;
  wire to_sc_37_for_or_nl;
  wire or_nl;
  wire mux_2_nl;
  wire mux_1_nl;
  wire or_67_nl;
  wire or_66_nl;

  // Interconnect Declarations for Component Instantiations 
  wire [4:0] nl_to_sc_37_1_for_to_sc_37_1_for_rshift_1_rg_a;
  assign nl_to_sc_37_1_for_to_sc_37_1_for_rshift_1_rg_a = {(fsm_output[6]) , l_S_i_0_i_i_3_0_sva_2_0
      , 1'b0};
  wire [5:0] nl_to_sc_37_1_for_to_sc_37_1_for_rshift_1_rg_s;
  assign nl_to_sc_37_1_for_to_sc_37_1_for_rshift_1_rg_s = {to_sc_37_1_for_i_1_0_sva_0
      , 5'b00000};
  wire  nl_feed_0_run_run_fsm_inst_v0_req_Push_1_do_C_1_tr0;
  assign nl_feed_0_run_run_fsm_inst_v0_req_Push_1_do_C_1_tr0 = ~ v0_req_rdy;
  wire  nl_feed_0_run_run_fsm_inst_to_sc_37_1_for_C_0_tr0;
  assign nl_feed_0_run_run_fsm_inst_to_sc_37_1_for_C_0_tr0 = ~ to_sc_37_1_for_i_1_0_sva_0;
  wire  nl_feed_0_run_run_fsm_inst_v2_Push_1_do_C_0_tr1;
  assign nl_feed_0_run_run_fsm_inst_v2_Push_1_do_C_0_tr1 = ~ v2_rdy;
  mgc_shift_r_v5 #(.width_a(32'sd5),
  .signd_a(32'sd0),
  .width_s(32'sd6),
  .width_z(32'sd5)) to_sc_37_1_for_to_sc_37_1_for_rshift_1_rg (
      .a(nl_to_sc_37_1_for_to_sc_37_1_for_rshift_1_rg_a[4:0]),
      .s(nl_to_sc_37_1_for_to_sc_37_1_for_rshift_1_rg_s[5:0]),
      .z(z_out)
    );
  feed_0_run_run_fsm feed_0_run_run_fsm_inst (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output),
      .to_sc_37_for_C_0_tr0(to_sc_37_1_for_i_1_0_sva_0),
      .v0_req_Push_1_do_C_1_tr0(nl_feed_0_run_run_fsm_inst_v0_req_Push_1_do_C_1_tr0),
      .v0_rsp_Pop_1_do_C_0_tr0(v0_rsp_vld),
      .v1_Push_1_do_C_0_tr0(v1_rdy),
      .to_sc_37_1_for_C_0_tr0(nl_feed_0_run_run_fsm_inst_to_sc_37_1_for_C_0_tr0),
      .v0_req_Push_3_do_C_1_tr0(v0_req_rdy),
      .v0_rsp_Pop_3_do_C_0_tr0(v0_rsp_vld),
      .v2_Push_1_do_C_0_tr0(and_dcpl_4),
      .v2_Push_1_do_C_0_tr1(nl_feed_0_run_run_fsm_inst_v2_Push_1_do_C_0_tr1)
    );
  assign v2_dat_and_cse = (fsm_output[9]) & v0_rsp_vld;
  assign v1_dat_and_cse = (fsm_output[4]) & v0_rsp_vld;
  assign v0_req_dat = {reg_v0_req_dat_ftd , reg_v0_req_dat_ftd_1 , 27'b000000000000000000000000000
      , reg_v0_req_dat_ftd_2 , reg_v0_req_dat_ftd_3};
  assign nand_4_cse = ~(v2_rdy & (l_S_i_0_i_acc_3_tmp[3]));
  assign reg_l_S_i_0_i_i_3_0_sva_2_l_S_i_0_i_i_l_S_i_0_i_i_and_cse = v2_rdy & (fsm_output[10]);
  assign to_sc_37_1_for_or_ssc = (to_sc_37_1_for_i_1_0_sva_0 & (fsm_output[6])) |
      to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_mx0c1;
  assign nl_l_S_i_0_i_acc_3_tmp = conv_u2s_3_4(l_S_i_0_i_i_3_0_sva_2_0) + 4'b0001;
  assign l_S_i_0_i_acc_3_tmp = nl_l_S_i_0_i_acc_3_tmp[3:0];
  assign and_dcpl_4 = v2_rdy & (~ (l_S_i_0_i_acc_3_tmp[3]));
  assign or_dcpl_8 = (fsm_output[8]) | (fsm_output[3]);
  assign or_dcpl_9 = (fsm_output[4]) | (fsm_output[9]);
  assign and_46_cse = v1_rdy & (fsm_output[5]);
  assign and_51_cse = v0_req_rdy & or_dcpl_8;
  assign v0_rsp_rdy_mx0c1 = v0_rsp_vld & or_dcpl_9;
  assign to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_mx0c1 = (fsm_output[8]) |
      (fsm_output[10]);
  assign to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_sva_mx0c2 = (fsm_output[9:7]!=3'b000);
  assign to_sc_37_1_for_i_1_0_sva_0_mx0c1 = or_dcpl_8 | (fsm_output[5]) | (fsm_output[10]);
  assign v0_req_dat_or_ssc = (fsm_output[7]) | (fsm_output[2]);
  assign mux_tmp = MUX_s_1_2_2(v2_rdy, (fsm_output[10]), to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_sva_mx0c2);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v2_dat <= 32'b00000000000000000000000000000000;
    end
    else if ( v2_dat_and_cse ) begin
      v2_dat <= v0_rsp_dat;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v2_vld <= 1'b0;
    end
    else if ( v2_dat_and_cse | ((~ v2_rdy) & (fsm_output[10])) | reg_l_S_i_0_i_i_3_0_sva_2_l_S_i_0_i_i_l_S_i_0_i_i_and_cse
        ) begin
      v2_vld <= ~ reg_l_S_i_0_i_i_3_0_sva_2_l_S_i_0_i_i_l_S_i_0_i_i_and_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v1_dat <= 32'b00000000000000000000000000000000;
    end
    else if ( v1_dat_and_cse ) begin
      v1_dat <= v0_rsp_dat;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v1_vld <= 1'b0;
    end
    else if ( ((~ v1_rdy) & (fsm_output[5])) | v1_dat_and_cse | and_46_cse ) begin
      v1_vld <= ~ and_46_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v0_rsp_rdy <= 1'b0;
    end
    else if ( and_51_cse | ((~ v0_rsp_vld) & or_dcpl_9) | v0_rsp_rdy_mx0c1 ) begin
      v0_rsp_rdy <= ~ v0_rsp_rdy_mx0c1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v0_req_vld <= 1'b0;
    end
    else if ( ((~ v0_req_rdy) & or_dcpl_8) | and_46_cse | (and_dcpl_4 & (fsm_output[10]))
        | (fsm_output[0]) | and_51_cse ) begin
      v0_req_vld <= ~ and_51_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      done <= 1'b0;
    end
    else if ( ~((~ (fsm_output[10])) | nand_4_cse) ) begin
      done <= 1'b1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      l_S_i_0_i_i_3_0_sva_2_0 <= 3'b000;
    end
    else if ( reg_l_S_i_0_i_i_3_0_sva_2_l_S_i_0_i_i_l_S_i_0_i_i_and_cse & nand_4_cse
        ) begin
      l_S_i_0_i_i_3_0_sva_2_0 <= l_S_i_0_i_acc_3_tmp[2:0];
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      to_sc_37_for_to_sc_37_for_rshift_3_0_sva <= 4'b0000;
    end
    else if ( (fsm_output[11]) | (fsm_output[0]) | (fsm_output[1]) ) begin
      to_sc_37_for_to_sc_37_for_rshift_3_0_sva <= z_out[3:0];
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_4 <= 1'b0;
      to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_3_0 <= 4'b0000;
    end
    else if ( to_sc_37_1_for_or_ssc ) begin
      to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_4 <= MUX_s_1_2_2((z_out[4]),
          reg_to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_1_ftd, to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_mx0c1);
      to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_3_0 <= MUX_v_4_2_2((z_out[3:0]),
          reg_to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_1_ftd_1, to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_mx0c1);
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      reg_to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_1_ftd <= 1'b0;
    end
    else if ( ~((~(v2_rdy | (fsm_output[0]) | (fsm_output[1]) | (fsm_output[3]) |
        (fsm_output[6]))) | to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_sva_mx0c2) )
        begin
      reg_to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_1_ftd <= z_out[4];
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      reg_to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_1_ftd_1 <= 4'b0000;
    end
    else if ( mux_2_nl | (fsm_output[6]) | (fsm_output[3]) ) begin
      reg_to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_1_ftd_1 <= MUX_v_4_2_2(to_sc_37_for_and_nl,
          (z_out[3:0]), or_nl);
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      to_sc_37_1_for_i_1_0_sva_0 <= 1'b1;
    end
    else if ( (fsm_output[6]) | (fsm_output[1]) | to_sc_37_1_for_i_1_0_sva_0_mx0c1
        ) begin
      to_sc_37_1_for_i_1_0_sva_0 <= to_sc_37_1_for_i_1_0_sva_0_mx0c1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      reg_v0_req_dat_ftd <= 1'b0;
      reg_v0_req_dat_ftd_1 <= 4'b0000;
      reg_v0_req_dat_ftd_2 <= 1'b0;
      reg_v0_req_dat_ftd_3 <= 4'b0000;
    end
    else if ( v0_req_dat_or_ssc ) begin
      reg_v0_req_dat_ftd <= to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_4 & (fsm_output[7]);
      reg_v0_req_dat_ftd_1 <= MUX_v_4_2_2(reg_to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_1_ftd_1,
          to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_lpi_2_3_0, fsm_output[7]);
      reg_v0_req_dat_ftd_2 <= reg_to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_1_ftd
          & (fsm_output[7]);
      reg_v0_req_dat_ftd_3 <= MUX_v_4_2_2(to_sc_37_for_to_sc_37_for_rshift_3_0_sva,
          reg_to_sc_37_1_for_to_sc_37_1_for_rshift_4_0_1_ftd_1, fsm_output[7]);
    end
  end
  assign to_sc_37_for_or_nl = (fsm_output[1]) | (fsm_output[3]) | (fsm_output[10]);
  assign to_sc_37_for_and_nl = MUX_v_4_2_2(4'b0000, to_sc_37_for_to_sc_37_for_rshift_3_0_sva,
      to_sc_37_for_or_nl);
  assign or_nl = (fsm_output[1]) | (fsm_output[6]);
  assign or_67_nl = (fsm_output[0]) | mux_tmp;
  assign mux_1_nl = MUX_s_1_2_2(or_67_nl, (fsm_output[10]), fsm_output[1]);
  assign or_66_nl = (fsm_output[1:0]!=2'b00) | mux_tmp;
  assign mux_2_nl = MUX_s_1_2_2(mux_1_nl, or_66_nl, to_sc_37_1_for_i_1_0_sva_0);

  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [3:0] MUX_v_4_2_2;
    input [3:0] input_0;
    input [3:0] input_1;
    input  sel;
    reg [3:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_4_2_2 = result;
  end
  endfunction


  function automatic [3:0] conv_u2s_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_4 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    mul_0_run
// ------------------------------------------------------------------


module mul_0_run (
  clk, rst, done, v6_vld, v6_rdy, v6_dat, v7_vld, v7_rdy, v7_dat, v8
);
  input clk;
  input rst;
  output done;
  reg done;
  input v6_vld;
  output v6_rdy;
  reg v6_rdy;
  input [31:0] v6_dat;
  input v7_vld;
  output v7_rdy;
  reg v7_rdy;
  input [31:0] v7_dat;
  output [31:0] v8;
  reg [31:0] v8;
  wire [64:0] nl_v8;


  // Interconnect Declarations
  wire [3:0] fsm_output;
  wire [3:0] l_S_i_0_i1_acc_1_tmp;
  wire [4:0] nl_l_S_i_0_i1_acc_1_tmp;
  wire and_dcpl;
  wire and_4_cse;
  wire nand_1_cse;
  wire v8_and_cse;
  reg [31:0] l_S_i_0_i1_v10_sva;
  reg [2:0] l_S_i_0_i1_i1_3_0_sva_2_0;


  // Interconnect Declarations for Component Instantiations 
  wire  nl_mul_0_run_run_fsm_inst_v6_Pop_1_do_C_0_tr0;
  assign nl_mul_0_run_run_fsm_inst_v6_Pop_1_do_C_0_tr0 = ~ v6_vld;
  wire  nl_mul_0_run_run_fsm_inst_v7_Pop_1_do_C_0_tr1;
  assign nl_mul_0_run_run_fsm_inst_v7_Pop_1_do_C_0_tr1 = ~ v7_vld;
  mul_0_run_run_fsm mul_0_run_run_fsm_inst (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output),
      .v6_Pop_1_do_C_0_tr0(nl_mul_0_run_run_fsm_inst_v6_Pop_1_do_C_0_tr0),
      .v7_Pop_1_do_C_0_tr0(and_dcpl),
      .v7_Pop_1_do_C_0_tr1(nl_mul_0_run_run_fsm_inst_v7_Pop_1_do_C_0_tr1)
    );
  assign v8_and_cse = (fsm_output[2]) & v7_vld;
  assign nand_1_cse = ~(v7_vld & (l_S_i_0_i1_acc_1_tmp[3]));
  assign nl_l_S_i_0_i1_acc_1_tmp = conv_u2s_3_4(l_S_i_0_i1_i1_3_0_sva_2_0) + 4'b0001;
  assign l_S_i_0_i1_acc_1_tmp = nl_l_S_i_0_i1_acc_1_tmp[3:0];
  assign and_dcpl = v7_vld & (~ (l_S_i_0_i1_acc_1_tmp[3]));
  assign and_4_cse = v6_vld & (fsm_output[1]);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v8 <= 32'b00000000000000000000000000000000;
    end
    else if ( v8_and_cse ) begin
      v8 <= nl_v8[31:0];
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v7_rdy <= 1'b0;
    end
    else if ( and_4_cse | ((~ v7_vld) & (fsm_output[2])) | v8_and_cse ) begin
      v7_rdy <= ~ v8_and_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v6_rdy <= 1'b0;
    end
    else if ( ((~ v6_vld) & (fsm_output[1])) | (and_dcpl & (fsm_output[2])) | (fsm_output[0])
        | and_4_cse ) begin
      v6_rdy <= ~ and_4_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      done <= 1'b0;
    end
    else if ( ~((~ (fsm_output[2])) | nand_1_cse) ) begin
      done <= 1'b1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      l_S_i_0_i1_i1_3_0_sva_2_0 <= 3'b000;
    end
    else if ( v8_and_cse & nand_1_cse ) begin
      l_S_i_0_i1_i1_3_0_sva_2_0 <= l_S_i_0_i1_acc_1_tmp[2:0];
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      l_S_i_0_i1_v10_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( (~ (fsm_output[2])) & v6_vld ) begin
      l_S_i_0_i1_v10_sva <= v6_dat;
    end
  end
  assign nl_v8  = $signed(l_S_i_0_i1_v10_sva) * $signed(conv_u2s_32_33(v7_dat));

  function automatic [3:0] conv_u2s_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_4 =  {1'b0, vector};
  end
  endfunction


  function automatic [32:0] conv_u2s_32_33 ;
    input [31:0]  vector ;
  begin
    conv_u2s_32_33 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    acc_0_run
// ------------------------------------------------------------------


module acc_0_run (
  clk, rst, done, v22, v23_vld, v23_rdy, v23_dat
);
  input clk;
  input rst;
  output done;
  reg done;
  input [31:0] v22;
  output v23_vld;
  reg v23_vld;
  input v23_rdy;
  output [31:0] v23_dat;
  reg [31:0] v23_dat;


  // Interconnect Declarations
  wire [3:0] fsm_output;
  wire [3:0] l_S_i_0_i2_acc_1_tmp;
  wire [4:0] nl_l_S_i_0_i2_acc_1_tmp;
  wire and_dcpl;
  wire nand_cse;
  reg [2:0] l_S_i_0_i2_i2_3_0_sva_2_0;
  wire v23_dat_mx0c1;
  wire v23_vld_mx0c1;

  wire[31:0] l_S_i_0_i2_v32_acc_1_nl;
  wire[32:0] nl_l_S_i_0_i2_v32_acc_1_nl;

  // Interconnect Declarations for Component Instantiations 
  wire  nl_acc_0_run_run_fsm_inst_v23_Push_1_do_C_0_tr0;
  assign nl_acc_0_run_run_fsm_inst_v23_Push_1_do_C_0_tr0 = ~ v23_rdy;
  acc_0_run_run_fsm acc_0_run_run_fsm_inst (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output),
      .v23_Push_1_do_C_0_tr0(nl_acc_0_run_run_fsm_inst_v23_Push_1_do_C_0_tr0),
      .v23_Push_1_do_C_0_tr1(and_dcpl)
    );
  assign nand_cse = ~(v23_rdy & (l_S_i_0_i2_acc_1_tmp[3]));
  assign nl_l_S_i_0_i2_acc_1_tmp = conv_u2s_3_4(l_S_i_0_i2_i2_3_0_sva_2_0) + 4'b0001;
  assign l_S_i_0_i2_acc_1_tmp = nl_l_S_i_0_i2_acc_1_tmp[3:0];
  assign and_dcpl = v23_rdy & (~ (l_S_i_0_i2_acc_1_tmp[3]));
  assign v23_dat_mx0c1 = and_dcpl & (fsm_output[1]);
  assign v23_vld_mx0c1 = v23_rdy & (l_S_i_0_i2_acc_1_tmp[3]) & (fsm_output[1]);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v23_dat <= 32'b00000000000000000000000000000000;
    end
    else if ( (fsm_output[0]) | v23_dat_mx0c1 ) begin
      v23_dat <= MUX_v_32_2_2(v22, l_S_i_0_i2_v32_acc_1_nl, v23_dat_mx0c1);
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v23_vld <= 1'b0;
    end
    else if ( (nand_cse & (fsm_output[1])) | (fsm_output[0]) | v23_vld_mx0c1 ) begin
      v23_vld <= ~ v23_vld_mx0c1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      done <= 1'b0;
    end
    else if ( ~((~ (fsm_output[1])) | nand_cse) ) begin
      done <= 1'b1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      l_S_i_0_i2_i2_3_0_sva_2_0 <= 3'b000;
    end
    else if ( v23_rdy & (fsm_output[1]) & nand_cse ) begin
      l_S_i_0_i2_i2_3_0_sva_2_0 <= l_S_i_0_i2_acc_1_tmp[2:0];
    end
  end
  assign nl_l_S_i_0_i2_v32_acc_1_nl = v23_dat + v22;
  assign l_S_i_0_i2_v32_acc_1_nl = nl_l_S_i_0_i2_v32_acc_1_nl[31:0];

  function automatic [31:0] MUX_v_32_2_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input  sel;
    reg [31:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_32_2_2 = result;
  end
  endfunction


  function automatic [3:0] conv_u2s_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_4 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    sink_0_run
// ------------------------------------------------------------------


module sink_0_run (
  clk, rst, done, v35_vld, v35_rdy, v35_dat, v36_vld, v36_rdy, v36_dat
);
  input clk;
  input rst;
  output done;
  reg done;
  output v35_vld;
  reg v35_vld;
  input v35_rdy;
  output [31:0] v35_dat;
  reg [31:0] v35_dat;
  input v36_vld;
  output v36_rdy;
  reg v36_rdy;
  input [31:0] v36_dat;


  // Interconnect Declarations
  wire [3:0] fsm_output;
  wire [3:0] l_S_i_0_i3_acc_1_tmp;
  wire [4:0] nl_l_S_i_0_i3_acc_1_tmp;
  wire and_dcpl;
  wire nand_2_cse;
  wire v35_dat_and_cse;
  wire reg_l_S_i_0_i3_i3_3_0_sva_2_l_S_i_0_i3_i3_l_S_i_0_i3_i3_and_cse;
  reg [2:0] l_S_i_0_i3_i3_3_0_sva_2_0;


  // Interconnect Declarations for Component Instantiations 
  wire  nl_sink_0_run_run_fsm_inst_v36_Pop_1_do_C_0_tr0;
  assign nl_sink_0_run_run_fsm_inst_v36_Pop_1_do_C_0_tr0 = ~ v36_vld;
  wire  nl_sink_0_run_run_fsm_inst_v35_Push_1_do_C_0_tr1;
  assign nl_sink_0_run_run_fsm_inst_v35_Push_1_do_C_0_tr1 = ~ v35_rdy;
  sink_0_run_run_fsm sink_0_run_run_fsm_inst (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output),
      .v36_Pop_1_do_C_0_tr0(nl_sink_0_run_run_fsm_inst_v36_Pop_1_do_C_0_tr0),
      .v35_Push_1_do_C_0_tr0(and_dcpl),
      .v35_Push_1_do_C_0_tr1(nl_sink_0_run_run_fsm_inst_v35_Push_1_do_C_0_tr1)
    );
  assign v35_dat_and_cse = (fsm_output[1]) & v36_vld;
  assign nand_2_cse = ~(v35_rdy & (l_S_i_0_i3_acc_1_tmp[3]));
  assign reg_l_S_i_0_i3_i3_3_0_sva_2_l_S_i_0_i3_i3_l_S_i_0_i3_i3_and_cse = v35_rdy
      & (fsm_output[2]);
  assign nl_l_S_i_0_i3_acc_1_tmp = conv_u2s_3_4(l_S_i_0_i3_i3_3_0_sva_2_0) + 4'b0001;
  assign l_S_i_0_i3_acc_1_tmp = nl_l_S_i_0_i3_acc_1_tmp[3:0];
  assign and_dcpl = v35_rdy & (~ (l_S_i_0_i3_acc_1_tmp[3]));
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v36_rdy <= 1'b0;
    end
    else if ( ((~ v36_vld) & (fsm_output[1])) | (and_dcpl & (fsm_output[2])) | (fsm_output[0])
        | v35_dat_and_cse ) begin
      v36_rdy <= ~ v35_dat_and_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v35_dat <= 32'b00000000000000000000000000000000;
    end
    else if ( v35_dat_and_cse ) begin
      v35_dat <= v36_dat;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v35_vld <= 1'b0;
    end
    else if ( v35_dat_and_cse | ((~ v35_rdy) & (fsm_output[2])) | reg_l_S_i_0_i3_i3_3_0_sva_2_l_S_i_0_i3_i3_l_S_i_0_i3_i3_and_cse
        ) begin
      v35_vld <= ~ reg_l_S_i_0_i3_i3_3_0_sva_2_l_S_i_0_i3_i3_l_S_i_0_i3_i3_and_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      done <= 1'b0;
    end
    else if ( ~((~ (fsm_output[2])) | nand_2_cse) ) begin
      done <= 1'b1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      l_S_i_0_i3_i3_3_0_sva_2_0 <= 3'b000;
    end
    else if ( reg_l_S_i_0_i3_i3_3_0_sva_2_l_S_i_0_i3_i3_l_S_i_0_i3_i3_and_cse & nand_2_cse
        ) begin
      l_S_i_0_i3_i3_3_0_sva_2_0 <= l_S_i_0_i3_acc_1_tmp[2:0];
    end
  end

  function automatic [3:0] conv_u2s_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_4 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    AlloMem_ac_int_32_true_16_4_32_run
// ------------------------------------------------------------------


module AlloMem_ac_int_32_true_16_4_32_run (
  clk, rst, req_vld, req_rdy, req_dat, rsp_vld, rsp_rdy, rsp_dat
);
  input clk;
  input rst;
  input req_vld;
  output req_rdy;
  reg req_rdy;
  input [36:0] req_dat;
  output rsp_vld;
  reg rsp_vld;
  input rsp_rdy;
  output [31:0] rsp_dat;


  // Interconnect Declarations
  wire [5:0] fsm_output;
  wire and_dcpl_4;
  wire and_dcpl_5;
  wire and_dcpl_6;
  wire and_dcpl_8;
  wire and_dcpl_9;
  wire and_dcpl_11;
  wire and_dcpl_13;
  wire and_dcpl_15;
  wire and_dcpl_20;
  wire and_dcpl_25;
  reg [4:0] to_ac_37_r_sva_1_4_0;
  reg to_ac_37_for_i_0_sva;
  wire to_ac_37_for_mux_1_tmp_0;
  wire rsp_vld_mx0c1;
  wire req_rdy_mx0c1;
  reg [31:0] to_ac_37_v_36_0_sva_36_5;
  reg [4:0] to_ac_37_v_36_0_sva_4_0;
  wire to_ac_37_r_and_ssc;
  reg [4:0] reg_to_ac_37_r_sva_1_36_5_ftd;
  reg [26:0] reg_to_ac_37_r_sva_1_36_5_ftd_1;
  reg [4:0] mem_0_sva_rsp_0;
  reg [26:0] mem_0_sva_rsp_1;
  wire and_89_ssc;
  reg [4:0] mem_1_sva_rsp_0;
  reg [26:0] mem_1_sva_rsp_1;
  wire and_91_ssc;
  reg [4:0] mem_2_sva_rsp_0;
  reg [26:0] mem_2_sva_rsp_1;
  wire and_93_ssc;
  reg [4:0] mem_3_sva_rsp_0;
  reg [26:0] mem_3_sva_rsp_1;
  wire and_95_ssc;
  reg [4:0] mem_4_sva_rsp_0;
  reg [26:0] mem_4_sva_rsp_1;
  wire and_97_ssc;
  reg [4:0] mem_5_sva_rsp_0;
  reg [26:0] mem_5_sva_rsp_1;
  wire and_99_ssc;
  reg [4:0] mem_6_sva_rsp_0;
  reg [26:0] mem_6_sva_rsp_1;
  wire and_101_ssc;
  reg [4:0] mem_7_sva_rsp_0;
  reg [26:0] mem_7_sva_rsp_1;
  wire and_103_ssc;
  reg [4:0] mem_8_sva_rsp_0;
  reg [26:0] mem_8_sva_rsp_1;
  wire and_105_ssc;
  reg [4:0] mem_9_sva_rsp_0;
  reg [26:0] mem_9_sva_rsp_1;
  wire and_107_ssc;
  reg [4:0] mem_10_sva_rsp_0;
  reg [26:0] mem_10_sva_rsp_1;
  wire and_109_ssc;
  reg [4:0] mem_11_sva_rsp_0;
  reg [26:0] mem_11_sva_rsp_1;
  wire and_111_ssc;
  reg [4:0] mem_12_sva_rsp_0;
  reg [26:0] mem_12_sva_rsp_1;
  wire and_113_ssc;
  reg [4:0] mem_13_sva_rsp_0;
  reg [26:0] mem_13_sva_rsp_1;
  wire and_115_ssc;
  reg [4:0] mem_14_sva_rsp_0;
  reg [26:0] mem_14_sva_rsp_1;
  wire and_117_ssc;
  reg [4:0] mem_15_sva_rsp_0;
  reg [26:0] mem_15_sva_rsp_1;
  wire and_119_ssc;
  reg [4:0] reg_rsp_dat_ftd;
  reg [26:0] reg_rsp_dat_ftd_1;

  wire not_nl;

  // Interconnect Declarations for Component Instantiations 
  wire  nl_AlloMem_ac_int_32_true_16_4_32_run_run_fsm_inst_to_ac_37_for_C_0_tr0;
  assign nl_AlloMem_ac_int_32_true_16_4_32_run_run_fsm_inst_to_ac_37_for_C_0_tr0
      = to_ac_37_for_i_0_sva & to_ac_37_for_mux_1_tmp_0;
  wire  nl_AlloMem_ac_int_32_true_16_4_32_run_run_fsm_inst_to_ac_37_for_C_0_tr1;
  assign nl_AlloMem_ac_int_32_true_16_4_32_run_run_fsm_inst_to_ac_37_for_C_0_tr1
      = to_ac_37_for_i_0_sva & (~ to_ac_37_for_mux_1_tmp_0);
  AlloMem_ac_int_32_true_16_4_32_run_run_fsm AlloMem_ac_int_32_true_16_4_32_run_run_fsm_inst
      (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output),
      .req_Pop_1_do_C_0_tr0(req_vld),
      .to_ac_37_for_C_0_tr0(nl_AlloMem_ac_int_32_true_16_4_32_run_run_fsm_inst_to_ac_37_for_C_0_tr0),
      .to_ac_37_for_C_0_tr1(nl_AlloMem_ac_int_32_true_16_4_32_run_run_fsm_inst_to_ac_37_for_C_0_tr1),
      .rsp_Push_1_do_C_1_tr0(rsp_rdy)
    );
  assign rsp_dat = {reg_rsp_dat_ftd , reg_rsp_dat_ftd_1};
  assign to_ac_37_r_and_ssc = (fsm_output[4:3]==2'b00) & ((~ to_ac_37_for_i_0_sva)
      | to_ac_37_for_mux_1_tmp_0);
  assign to_ac_37_for_mux_1_tmp_0 = MUX_s_1_2_2((to_ac_37_v_36_0_sva_4_0[0]), (to_ac_37_r_sva_1_4_0[0]),
      to_ac_37_for_i_0_sva);
  assign and_dcpl_4 = ~((to_ac_37_r_sva_1_4_0[4:3]!=2'b00));
  assign and_dcpl_5 = (to_ac_37_r_sva_1_4_0[1:0]==2'b01);
  assign and_dcpl_6 = and_dcpl_5 & (~ (to_ac_37_r_sva_1_4_0[2]));
  assign and_dcpl_8 = (to_ac_37_r_sva_1_4_0[1:0]==2'b11);
  assign and_dcpl_9 = and_dcpl_8 & (~ (to_ac_37_r_sva_1_4_0[2]));
  assign and_dcpl_11 = and_dcpl_5 & (to_ac_37_r_sva_1_4_0[2]);
  assign and_dcpl_13 = and_dcpl_8 & (to_ac_37_r_sva_1_4_0[2]);
  assign and_dcpl_15 = (to_ac_37_r_sva_1_4_0[4:3]==2'b01);
  assign and_dcpl_20 = (to_ac_37_r_sva_1_4_0[4:3]==2'b10);
  assign and_dcpl_25 = (to_ac_37_r_sva_1_4_0[4:3]==2'b11);
  assign rsp_vld_mx0c1 = rsp_rdy & (fsm_output[4]);
  assign req_rdy_mx0c1 = req_vld & (fsm_output[1]);
  assign and_89_ssc = and_dcpl_6 & and_dcpl_4 & (fsm_output[5]);
  assign and_91_ssc = and_dcpl_9 & and_dcpl_4 & (fsm_output[5]);
  assign and_93_ssc = and_dcpl_11 & and_dcpl_4 & (fsm_output[5]);
  assign and_95_ssc = and_dcpl_13 & and_dcpl_4 & (fsm_output[5]);
  assign and_97_ssc = and_dcpl_6 & and_dcpl_15 & (fsm_output[5]);
  assign and_99_ssc = and_dcpl_9 & and_dcpl_15 & (fsm_output[5]);
  assign and_101_ssc = and_dcpl_11 & and_dcpl_15 & (fsm_output[5]);
  assign and_103_ssc = and_dcpl_13 & and_dcpl_15 & (fsm_output[5]);
  assign and_105_ssc = and_dcpl_6 & and_dcpl_20 & (fsm_output[5]);
  assign and_107_ssc = and_dcpl_9 & and_dcpl_20 & (fsm_output[5]);
  assign and_109_ssc = and_dcpl_11 & and_dcpl_20 & (fsm_output[5]);
  assign and_111_ssc = and_dcpl_13 & and_dcpl_20 & (fsm_output[5]);
  assign and_113_ssc = and_dcpl_6 & and_dcpl_25 & (fsm_output[5]);
  assign and_115_ssc = and_dcpl_9 & and_dcpl_25 & (fsm_output[5]);
  assign and_117_ssc = and_dcpl_11 & and_dcpl_25 & (fsm_output[5]);
  assign and_119_ssc = and_dcpl_13 & and_dcpl_25 & (fsm_output[5]);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      reg_rsp_dat_ftd <= 5'b00000;
    end
    else if ( fsm_output[3] ) begin
      reg_rsp_dat_ftd <= MUX_v_5_16_2(mem_0_sva_rsp_0, mem_1_sva_rsp_0, mem_2_sva_rsp_0,
          mem_3_sva_rsp_0, mem_4_sva_rsp_0, mem_5_sva_rsp_0, mem_6_sva_rsp_0, mem_7_sva_rsp_0,
          mem_8_sva_rsp_0, mem_9_sva_rsp_0, mem_10_sva_rsp_0, mem_11_sva_rsp_0, mem_12_sva_rsp_0,
          mem_13_sva_rsp_0, mem_14_sva_rsp_0, mem_15_sva_rsp_0, to_ac_37_r_sva_1_4_0[4:1]);
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      reg_rsp_dat_ftd_1 <= 27'b000000000000000000000000000;
    end
    else if ( fsm_output[3] ) begin
      reg_rsp_dat_ftd_1 <= MUX_v_27_16_2(mem_0_sva_rsp_1, mem_1_sva_rsp_1, mem_2_sva_rsp_1,
          mem_3_sva_rsp_1, mem_4_sva_rsp_1, mem_5_sva_rsp_1, mem_6_sva_rsp_1, mem_7_sva_rsp_1,
          mem_8_sva_rsp_1, mem_9_sva_rsp_1, mem_10_sva_rsp_1, mem_11_sva_rsp_1, mem_12_sva_rsp_1,
          mem_13_sva_rsp_1, mem_14_sva_rsp_1, mem_15_sva_rsp_1, to_ac_37_r_sva_1_4_0[4:1]);
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      rsp_vld <= 1'b0;
    end
    else if ( (fsm_output[3]) | rsp_vld_mx0c1 ) begin
      rsp_vld <= ~ rsp_vld_mx0c1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      req_rdy <= 1'b0;
    end
    else if ( ((~ req_vld) & (fsm_output[1])) | (fsm_output[0]) | req_rdy_mx0c1 )
        begin
      req_rdy <= ~ req_rdy_mx0c1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      to_ac_37_for_i_0_sva <= 1'b0;
      to_ac_37_v_36_0_sva_36_5 <= 32'b00000000000000000000000000000000;
      to_ac_37_v_36_0_sva_4_0 <= 5'b00000;
    end
    else begin
      to_ac_37_for_i_0_sva <= fsm_output[2];
      to_ac_37_v_36_0_sva_36_5 <= MUX_v_32_2_2(32'b00000000000000000000000000000000,
          (req_dat[36:5]), not_nl);
      to_ac_37_v_36_0_sva_4_0 <= MUX_v_5_2_2((req_dat[4:0]), (to_ac_37_v_36_0_sva_36_5[31:27]),
          fsm_output[2]);
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      to_ac_37_r_sva_1_4_0 <= 5'b00000;
    end
    else if ( ~((~ (fsm_output[2])) | to_ac_37_for_i_0_sva) ) begin
      to_ac_37_r_sva_1_4_0 <= to_ac_37_v_36_0_sva_4_0;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      reg_to_ac_37_r_sva_1_36_5_ftd <= 5'b00000;
    end
    else if ( to_ac_37_r_and_ssc ) begin
      reg_to_ac_37_r_sva_1_36_5_ftd <= to_ac_37_v_36_0_sva_4_0;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      reg_to_ac_37_r_sva_1_36_5_ftd_1 <= 27'b000000000000000000000000000;
    end
    else if ( to_ac_37_r_and_ssc & (~ to_ac_37_for_i_0_sva) ) begin
      reg_to_ac_37_r_sva_1_36_5_ftd_1 <= to_ac_37_v_36_0_sva_36_5[26:0];
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_0_sva_rsp_0 <= 5'b00000;
      mem_0_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_89_ssc ) begin
      mem_0_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_0_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_1_sva_rsp_0 <= 5'b00000;
      mem_1_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_91_ssc ) begin
      mem_1_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_1_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_2_sva_rsp_0 <= 5'b00000;
      mem_2_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_93_ssc ) begin
      mem_2_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_2_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_3_sva_rsp_0 <= 5'b00000;
      mem_3_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_95_ssc ) begin
      mem_3_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_3_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_4_sva_rsp_0 <= 5'b00000;
      mem_4_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_97_ssc ) begin
      mem_4_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_4_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_5_sva_rsp_0 <= 5'b00000;
      mem_5_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_99_ssc ) begin
      mem_5_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_5_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_6_sva_rsp_0 <= 5'b00000;
      mem_6_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_101_ssc ) begin
      mem_6_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_6_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_7_sva_rsp_0 <= 5'b00000;
      mem_7_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_103_ssc ) begin
      mem_7_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_7_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_8_sva_rsp_0 <= 5'b00000;
      mem_8_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_105_ssc ) begin
      mem_8_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_8_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_9_sva_rsp_0 <= 5'b00000;
      mem_9_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_107_ssc ) begin
      mem_9_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_9_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_10_sva_rsp_0 <= 5'b00000;
      mem_10_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_109_ssc ) begin
      mem_10_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_10_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_11_sva_rsp_0 <= 5'b00000;
      mem_11_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_111_ssc ) begin
      mem_11_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_11_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_12_sva_rsp_0 <= 5'b00000;
      mem_12_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_113_ssc ) begin
      mem_12_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_12_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_13_sva_rsp_0 <= 5'b00000;
      mem_13_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_115_ssc ) begin
      mem_13_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_13_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_14_sva_rsp_0 <= 5'b00000;
      mem_14_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_117_ssc ) begin
      mem_14_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_14_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      mem_15_sva_rsp_0 <= 5'b00000;
      mem_15_sva_rsp_1 <= 27'b000000000000000000000000000;
    end
    else if ( and_119_ssc ) begin
      mem_15_sva_rsp_0 <= reg_to_ac_37_r_sva_1_36_5_ftd;
      mem_15_sva_rsp_1 <= reg_to_ac_37_r_sva_1_36_5_ftd_1;
    end
  end
  assign not_nl = ~ (fsm_output[2]);

  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [26:0] MUX_v_27_16_2;
    input [26:0] input_0;
    input [26:0] input_1;
    input [26:0] input_2;
    input [26:0] input_3;
    input [26:0] input_4;
    input [26:0] input_5;
    input [26:0] input_6;
    input [26:0] input_7;
    input [26:0] input_8;
    input [26:0] input_9;
    input [26:0] input_10;
    input [26:0] input_11;
    input [26:0] input_12;
    input [26:0] input_13;
    input [26:0] input_14;
    input [26:0] input_15;
    input [3:0] sel;
    reg [26:0] result;
  begin
    case (sel)
      4'b0000 : begin
        result = input_0;
      end
      4'b0001 : begin
        result = input_1;
      end
      4'b0010 : begin
        result = input_2;
      end
      4'b0011 : begin
        result = input_3;
      end
      4'b0100 : begin
        result = input_4;
      end
      4'b0101 : begin
        result = input_5;
      end
      4'b0110 : begin
        result = input_6;
      end
      4'b0111 : begin
        result = input_7;
      end
      4'b1000 : begin
        result = input_8;
      end
      4'b1001 : begin
        result = input_9;
      end
      4'b1010 : begin
        result = input_10;
      end
      4'b1011 : begin
        result = input_11;
      end
      4'b1100 : begin
        result = input_12;
      end
      4'b1101 : begin
        result = input_13;
      end
      4'b1110 : begin
        result = input_14;
      end
      default : begin
        result = input_15;
      end
    endcase
    MUX_v_27_16_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_2_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input  sel;
    reg [31:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_32_2_2 = result;
  end
  endfunction


  function automatic [4:0] MUX_v_5_16_2;
    input [4:0] input_0;
    input [4:0] input_1;
    input [4:0] input_2;
    input [4:0] input_3;
    input [4:0] input_4;
    input [4:0] input_5;
    input [4:0] input_6;
    input [4:0] input_7;
    input [4:0] input_8;
    input [4:0] input_9;
    input [4:0] input_10;
    input [4:0] input_11;
    input [4:0] input_12;
    input [4:0] input_13;
    input [4:0] input_14;
    input [4:0] input_15;
    input [3:0] sel;
    reg [4:0] result;
  begin
    case (sel)
      4'b0000 : begin
        result = input_0;
      end
      4'b0001 : begin
        result = input_1;
      end
      4'b0010 : begin
        result = input_2;
      end
      4'b0011 : begin
        result = input_3;
      end
      4'b0100 : begin
        result = input_4;
      end
      4'b0101 : begin
        result = input_5;
      end
      4'b0110 : begin
        result = input_6;
      end
      4'b0111 : begin
        result = input_7;
      end
      4'b1000 : begin
        result = input_8;
      end
      4'b1001 : begin
        result = input_9;
      end
      4'b1010 : begin
        result = input_10;
      end
      4'b1011 : begin
        result = input_11;
      end
      4'b1100 : begin
        result = input_12;
      end
      4'b1101 : begin
        result = input_13;
      end
      4'b1110 : begin
        result = input_14;
      end
      default : begin
        result = input_15;
      end
    endcase
    MUX_v_5_16_2 = result;
  end
  endfunction


  function automatic [4:0] MUX_v_5_2_2;
    input [4:0] input_0;
    input [4:0] input_1;
    input  sel;
    reg [4:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_5_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    AlloFifo_ac_int_32_true_2
// ------------------------------------------------------------------


module AlloFifo_ac_int_32_true_2 (
  clk, rst, in_vld, in_rdy, in_dat, out_vld, out_rdy, out_dat
);
  input clk;
  input rst;
  input in_vld;
  output in_rdy;
  input [31:0] in_dat;
  output out_vld;
  input out_rdy;
  output [31:0] out_dat;


  // Interconnect Declarations
  wire [31:0] buf_0;
  wire [31:0] buf_1;
  wire [31:0] buf_2;
  wire [1:0] head_s;
  wire [1:0] tail_s;


  // Interconnect Declarations for Component Instantiations 
  wire [31:0] nl_AlloFifo_ac_int_32_true_2_enq_thread_inst_head_s;
  assign nl_AlloFifo_ac_int_32_true_2_enq_thread_inst_head_s = {30'b0, head_s};
  wire [31:0] nl_AlloFifo_ac_int_32_true_2_deq_thread_inst_tail_s;
  assign nl_AlloFifo_ac_int_32_true_2_deq_thread_inst_tail_s = {30'b0, tail_s};
  AlloFifo_ac_int_32_true_2_enq_thread AlloFifo_ac_int_32_true_2_enq_thread_inst
      (
      .clk(clk),
      .rst(rst),
      .in_vld(in_vld),
      .in_rdy(in_rdy),
      .in_dat(in_dat),
      .buf_0(buf_0),
      .buf_1(buf_1),
      .buf_2(buf_2),
      .head_s(nl_AlloFifo_ac_int_32_true_2_enq_thread_inst_head_s[31:0]),
      .tail_s(tail_s)
    );
  AlloFifo_ac_int_32_true_2_deq_thread AlloFifo_ac_int_32_true_2_deq_thread_inst
      (
      .clk(clk),
      .rst(rst),
      .out_vld(out_vld),
      .out_rdy(out_rdy),
      .out_dat(out_dat),
      .buf_0(buf_0),
      .buf_1(buf_1),
      .buf_2(buf_2),
      .head_s(head_s),
      .tail_s(nl_AlloFifo_ac_int_32_true_2_deq_thread_inst_tail_s[31:0])
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    feed_0
// ------------------------------------------------------------------


module feed_0 (
  clk, rst, done, v0_req_vld, v0_req_rdy, v0_req_dat, v0_rsp_vld, v0_rsp_rdy, v0_rsp_dat,
      v1_vld, v1_rdy, v1_dat, v2_vld, v2_rdy, v2_dat
);
  input clk;
  input rst;
  output done;
  output v0_req_vld;
  input v0_req_rdy;
  output [36:0] v0_req_dat;
  input v0_rsp_vld;
  output v0_rsp_rdy;
  input [31:0] v0_rsp_dat;
  output v1_vld;
  input v1_rdy;
  output [31:0] v1_dat;
  output v2_vld;
  input v2_rdy;
  output [31:0] v2_dat;



  // Interconnect Declarations for Component Instantiations 
  feed_0_run feed_0_run_inst (
      .clk(clk),
      .rst(rst),
      .done(done),
      .v0_req_vld(v0_req_vld),
      .v0_req_rdy(v0_req_rdy),
      .v0_req_dat(v0_req_dat),
      .v0_rsp_vld(v0_rsp_vld),
      .v0_rsp_rdy(v0_rsp_rdy),
      .v0_rsp_dat(v0_rsp_dat),
      .v1_vld(v1_vld),
      .v1_rdy(v1_rdy),
      .v1_dat(v1_dat),
      .v2_vld(v2_vld),
      .v2_rdy(v2_rdy),
      .v2_dat(v2_dat)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mul_0
// ------------------------------------------------------------------


module mul_0 (
  clk, rst, done, v6_vld, v6_rdy, v6_dat, v7_vld, v7_rdy, v7_dat, v8
);
  input clk;
  input rst;
  output done;
  input v6_vld;
  output v6_rdy;
  input [31:0] v6_dat;
  input v7_vld;
  output v7_rdy;
  input [31:0] v7_dat;
  output [31:0] v8;



  // Interconnect Declarations for Component Instantiations 
  mul_0_run mul_0_run_inst (
      .clk(clk),
      .rst(rst),
      .done(done),
      .v6_vld(v6_vld),
      .v6_rdy(v6_rdy),
      .v6_dat(v6_dat),
      .v7_vld(v7_vld),
      .v7_rdy(v7_rdy),
      .v7_dat(v7_dat),
      .v8(v8)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    acc_0
// ------------------------------------------------------------------


module acc_0 (
  clk, rst, done, v22, v23_vld, v23_rdy, v23_dat
);
  input clk;
  input rst;
  output done;
  input [31:0] v22;
  output v23_vld;
  input v23_rdy;
  output [31:0] v23_dat;



  // Interconnect Declarations for Component Instantiations 
  acc_0_run acc_0_run_inst (
      .clk(clk),
      .rst(rst),
      .done(done),
      .v22(v22),
      .v23_vld(v23_vld),
      .v23_rdy(v23_rdy),
      .v23_dat(v23_dat)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    sink_0
// ------------------------------------------------------------------


module sink_0 (
  clk, rst, done, v35_vld, v35_rdy, v35_dat, v36_vld, v36_rdy, v36_dat
);
  input clk;
  input rst;
  output done;
  output v35_vld;
  input v35_rdy;
  output [31:0] v35_dat;
  input v36_vld;
  output v36_rdy;
  input [31:0] v36_dat;



  // Interconnect Declarations for Component Instantiations 
  sink_0_run sink_0_run_inst (
      .clk(clk),
      .rst(rst),
      .done(done),
      .v35_vld(v35_vld),
      .v35_rdy(v35_rdy),
      .v35_dat(v35_dat),
      .v36_vld(v36_vld),
      .v36_rdy(v36_rdy),
      .v36_dat(v36_dat)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    AlloMem_ac_int_32_true_16_4_32
// ------------------------------------------------------------------


module AlloMem_ac_int_32_true_16_4_32 (
  clk, rst, req_vld, req_rdy, req_dat, rsp_vld, rsp_rdy, rsp_dat
);
  input clk;
  input rst;
  input req_vld;
  output req_rdy;
  input [36:0] req_dat;
  output rsp_vld;
  input rsp_rdy;
  output [31:0] rsp_dat;



  // Interconnect Declarations for Component Instantiations 
  AlloMem_ac_int_32_true_16_4_32_run AlloMem_ac_int_32_true_16_4_32_run_inst (
      .clk(clk),
      .rst(rst),
      .req_vld(req_vld),
      .req_rdy(req_rdy),
      .req_dat(req_dat),
      .rsp_vld(rsp_vld),
      .rsp_rdy(rsp_rdy),
      .rsp_dat(rsp_dat)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    pe_wire
// ------------------------------------------------------------------


module pe_wire (
  clk, rst, done, v40_vld, v40_rdy, v40_dat
);
  input clk;
  input rst;
  output done;
  output v40_vld;
  input v40_rdy;
  output [31:0] v40_dat;


  // Interconnect Declarations
  wire v41_in_vld;
  wire v41_in_rdy;
  wire [31:0] v41_in_dat;
  wire v41_out_vld;
  wire v41_out_rdy;
  wire [31:0] v41_out_dat;
  wire v42_in_vld;
  wire v42_in_rdy;
  wire [31:0] v42_in_dat;
  wire v42_out_vld;
  wire v42_out_rdy;
  wire [31:0] v42_out_dat;
  wire v43_in_vld;
  wire v43_in_rdy;
  wire [31:0] v43_in_dat;
  wire v43_out_vld;
  wire v43_out_rdy;
  wire [31:0] v43_out_dat;
  wire [31:0] v44;
  wire u0_done;
  wire u1_done;
  wire u2_done;
  wire u3_done;
  wire mp0_0_req_ch_vld;
  wire mp0_0_req_ch_rdy;
  wire [36:0] mp0_0_req_ch_dat;
  wire mp0_0_rsp_ch_vld;
  wire mp0_0_rsp_ch_rdy;
  wire [31:0] mp0_0_rsp_ch_dat;


  // Interconnect Declarations for Component Instantiations 
  AlloFifo_ac_int_32_true_2 v41_fifo (
      .clk(clk),
      .rst(rst),
      .in_vld(v41_in_vld),
      .in_rdy(v41_in_rdy),
      .in_dat(v41_in_dat),
      .out_vld(v41_out_vld),
      .out_rdy(v41_out_rdy),
      .out_dat(v41_out_dat)
    );
  AlloFifo_ac_int_32_true_2 v42_fifo (
      .clk(clk),
      .rst(rst),
      .in_vld(v42_in_vld),
      .in_rdy(v42_in_rdy),
      .in_dat(v42_in_dat),
      .out_vld(v42_out_vld),
      .out_rdy(v42_out_rdy),
      .out_dat(v42_out_dat)
    );
  AlloFifo_ac_int_32_true_2 v43_fifo (
      .clk(clk),
      .rst(rst),
      .in_vld(v43_in_vld),
      .in_rdy(v43_in_rdy),
      .in_dat(v43_in_dat),
      .out_vld(v43_out_vld),
      .out_rdy(v43_out_rdy),
      .out_dat(v43_out_dat)
    );
  feed_0 u0 (
      .clk(clk),
      .rst(rst),
      .done(u0_done),
      .v0_req_vld(mp0_0_req_ch_vld),
      .v0_req_rdy(mp0_0_req_ch_rdy),
      .v0_req_dat(mp0_0_req_ch_dat),
      .v0_rsp_vld(mp0_0_rsp_ch_vld),
      .v0_rsp_rdy(mp0_0_rsp_ch_rdy),
      .v0_rsp_dat(mp0_0_rsp_ch_dat),
      .v1_vld(v41_in_vld),
      .v1_rdy(v41_in_rdy),
      .v1_dat(v41_in_dat),
      .v2_vld(v42_in_vld),
      .v2_rdy(v42_in_rdy),
      .v2_dat(v42_in_dat)
    );
  mul_0 u1 (
      .clk(clk),
      .rst(rst),
      .done(u1_done),
      .v6_vld(v41_out_vld),
      .v6_rdy(v41_out_rdy),
      .v6_dat(v41_out_dat),
      .v7_vld(v42_out_vld),
      .v7_rdy(v42_out_rdy),
      .v7_dat(v42_out_dat),
      .v8(v44)
    );
  acc_0 u2 (
      .clk(clk),
      .rst(rst),
      .done(u2_done),
      .v22(v44),
      .v23_vld(v43_in_vld),
      .v23_rdy(v43_in_rdy),
      .v23_dat(v43_in_dat)
    );
  sink_0 u3 (
      .clk(clk),
      .rst(rst),
      .done(u3_done),
      .v35_vld(v40_vld),
      .v35_rdy(v40_rdy),
      .v35_dat(v40_dat),
      .v36_vld(v43_out_vld),
      .v36_rdy(v43_out_rdy),
      .v36_dat(v43_out_dat)
    );
  AlloMem_ac_int_32_true_16_4_32 mp0_0_mem (
      .clk(clk),
      .rst(rst),
      .req_vld(mp0_0_req_ch_vld),
      .req_rdy(mp0_0_req_ch_rdy),
      .req_dat(mp0_0_req_ch_dat),
      .rsp_vld(mp0_0_rsp_ch_vld),
      .rsp_rdy(mp0_0_rsp_ch_rdy),
      .rsp_dat(mp0_0_rsp_ch_dat)
    );
  pe_wire_comb pe_wire_comb_inst (
      .done(done),
      .u0_done(u0_done),
      .u1_done(u1_done),
      .u2_done(u2_done),
      .u3_done(u3_done)
    );
endmodule



