/*
 * rv_stream_ip -- an RV32I soft processor exposed to Allo as an hls::stream IP.
 *
 * Derived from anjn/vhls-riscv (https://github.com/anjn/vhls-riscv), file
 * kernel.cpp, which is itself a Vitis HLS port of the core from
 * chadyuu/riscv-chisel-book. The decode/execute/writeback logic below is
 * unmodified. Four changes turn it into something Allo can wire into a
 * dataflow region:
 *
 *   1. Interface. The original top took an ap_uint<8> memory array plus an
 *      ap_uint<32>* result pointer -- a memory-mapped processor, which is what
 *      every off-the-shelf HLS soft core looks like. Allo's IPModule needs
 *      hls::stream<T> ports to splice the IP into a dataflow graph, so the top
 *      now takes two hls::stream<int32_t> references instead; see the
 *      definition below.
 *
 *      NB: do not write the top's signature out in this comment. IPModule finds
 *      the function with the regex `(\w+)\s+<top>\s*\((.*?)\)\s*[{;]` over the
 *      whole file, so a `void <top>(...)` inside a comment matches first, and
 *      the non-greedy body then runs on to the real definition's `) {` --
 *      handing the parser several hundred lines as the parameter list.
 *
 *   2. Memory-mapped stream I/O. A load from MMIO_IN becomes sin.read(); a
 *      store to MMIO_OUT becomes sout.write(). Both addresses sit above
 *      MEM_SIZE, so they cannot alias real memory -- the core tests the address
 *      before touching local_mem. This is the standard way a CPU talks to a
 *      FIFO, and it means the *program* decides when to stream, not the wrapper.
 *
 *   3. Program in ROM. The original loaded a program through the mem[] port.
 *      A stream-only interface has no such port, so the program is a static
 *      array (generated by rvasm.py) copied into local_mem at reset.
 *
 *   4. Halt. The original break condition was `pc_reg == 0x44`, hardcoded for
 *      the riscv-tests convention. It is now HALT_PC, matching the program.
 *
 * Element type is int32_t, not ap_uint<32>, to match Allo's Stream[int32, D]:
 * the emitted declaration adopts Allo's stream type, so the C++ port type has
 * to agree with it.
 */
#ifndef __SYNTHESIS__
#include <iostream>
#endif

#include <hls_stream.h>
#include <stdint.h>
#include "ap_int.h"

// Small enough to synthesize quickly; the test programs are ~17 instructions.
const int MEM_SIZE = 1024;

// Memory-mapped stream ports (see note 2 above). All are >= MEM_SIZE, so a
// normal load/store can never reach them. Keep in sync with rvasm.py.
const int MMIO_IN = 0x8000;     // load  -> int32 in
const int MMIO_OUT = 0x8004;    // store -> int32 out
const int MMIO_IN17 = 0x8008;   // load  -> ap_uint<17> in  (EVA systolic word)
const int MMIO_OUT17 = 0x800C;  // store -> ap_uint<17> out
const int MMIO_OUT26 = 0x8010;  // store -> ap_uint<26> out (EVA router packet)
const int MMIO_OUT26B = 0x8014; // store -> second packet stream (west lane 1)

// EVA's systolic word: bit0 = valid, bits[1:17] = raw fp16. Allo emits
// Stream[UInt(17), D] as hls::stream< ap_uint<17> >, so the port must say
// exactly that.
typedef ap_uint<17> sys_word_t;

// EVA's router packet: {rq,id,mode,addr,data}. Allo emits Stream[UInt(26), D]
// as hls::stream< ap_uint<26> >.
typedef ap_uint<26> pkt_t;

// ---- Program ROM 1: vadd -------------------------------------------------
// 32 iterations of "read two words from the int32 stream, write their sum".
// Generated by rvasm.py: vadd_program(32).
const int HALT_PC = 0x24;
const ap_uint<32> PROGRAM[] = {
    0x000082b7,  // 0x00  lui  t0, 0x8       // t0 = MMIO_IN
    0x00428313,  // 0x04  addi t1, t0, 4     // t1 = MMIO_OUT
    0x02000393,  // 0x08  addi t2, x0, 32    // loop counter
    0x0002a503,  // 0x0c  lw   a0, 0(t0)     // a0 = sin.read()      <- loop
    0x0002a583,  // 0x10  lw   a1, 0(t0)     // a1 = sin.read()
    0x00b50633,  // 0x14  add  a2, a0, a1
    0x00c32023,  // 0x18  sw   a2, 0(t1)     // sout.write(a2)
    0xfff38393,  // 0x1c  addi t2, t2, -1
    0xfe0396e3,  // 0x20  bne  t2, x0, loop
};
const int PROGRAM_WORDS = sizeof(PROGRAM) / sizeof(PROGRAM[0]);

// ---- Program ROM 2: EVA east collector -----------------------------------
// Replaces the col_e kernel: primes credits, then per step reads a systolic
// word, returns a credit iff it was valid, and forwards the raw word to a
// drain kernel. Generated by rvasm.py: eva_collector_program(10, 6).
// NSTEP and PRIME_TOKENS are baked in -- the chip must use the same values.
const int COLLECTOR_NSTEP = 10;
const int COLLECTOR_PRIME_TOKENS = 6;
const int COLLECTOR_HALT_PC = 0x44;
const ap_uint<32> COLLECTOR_PROGRAM[] = {
    0x000082b7,  // 0x00  lui  t0, 0x8
    0x00828293,  // 0x04  addi t0, t0, 8      // t0 = MMIO_IN17
    0xffc28313,  // 0x08  addi t1, t0, -4     // t1 = MMIO_OUT (credits)
    0x00428e13,  // 0x0c  addi t3, t0, 4      // t3 = MMIO_OUT17 (results)
    0x00500393,  // 0x10  addi t2, x0, 5      // PRIME_TOKENS-1
    0x00032023,  // 0x14  sw   x0, 0(t1)      // scr_out.write(0)     <- prime loop
    0xfff38393,  // 0x18  addi t2, t2, -1
    0xfe039ce3,  // 0x1c  bne  t2, x0, prime
    0x00200693,  // 0x20  addi a3, x0, 2
    0x00d32023,  // 0x24  sw   a3, 0(t1)      // scr_out.write(2)
    0x00a00393,  // 0x28  addi t2, x0, 10     // NSTEP
    0x0002a503,  // 0x2c  lw   a0, 0(t0)      // w = sys_in.read()    <- main loop
    0x00157593,  // 0x30  andi a1, a0, 1      // vld = w & 1
    0x00b32023,  // 0x34  sw   a1, 0(t1)      // scr_out.write(vld)
    0x00ae2023,  // 0x38  sw   a0, 0(t3)      // res_out.write(w)
    0xfff38393,  // 0x3c  addi t2, t2, -1
    0xfe0396e3,  // 0x40  bne  t2, x0, loop
};
const int COLLECTOR_WORDS = sizeof(COLLECTOR_PROGRAM) / sizeof(COLLECTOR_PROGRAM[0]);

// ---- Program ROM 3: EVA PE programmer ------------------------------------
// Replaces the rdrv_w kernel at the array's west edge. Instead of replaying a
// host-supplied packet array it carries its own boot sequence: load the PE's
// instruction register file, load two operands into its data register file,
// set the iteration count, then set fetch_en -- at which point the PE starts
// executing the code the processor just gave it and sends its result east.
// Generated by rvasm.py:
//     eva_programmer_program(100, 6,
//         eva_boot_packets([pe_instr(ADD, SYSRGT, drf0, drf1)],
//                          [(0, 0x3c00), (1, 0x4000)], itsz=1))
//
// The 12 packets mirror eva_workloads.load_prog_packets exactly -- all 8 IRF
// slots (NOP-padded), then the DRF values, then config_reg_1, then
// config_reg_0 last. A shorter sequence that writes only the slots the kernel
// uses produces nothing at all; this was verified against the stock chip on
// Allo's CPU simulator before being baked in here.
//
// PROGRAMMER_NSTEP must equal the chip's NSTEP. 40 is not enough: at 1x1 the
// PE needs ~80 steps to boot, run and drain through the scoreboard and the
// credit-gated systolic port. (The chip's own load_mmm_router formula predicts
// 26, which is stale for this leanalu variant -- its golden MMM workload also
// needs ~120.)
const int PROGRAMMER_NSTEP = 100;
const int PROGRAMMER_PRIME_TOKENS = 6;
const int PROGRAMMER_HALT_PC = 0x60;
const ap_uint<32> PROGRAMMER_PROGRAM[] = {
    0x000082b7,  // 0x00  code
    0x01028313,  // 0x04  code
    0x06000413,  // 0x08  code
    0x00000493,  // 0x0c  code
    0x00c00913,  // 0x10  code
    0x00000713,  // 0x14  code
    0x00500393,  // 0x18  code
    0x00032023,  // 0x1c  code
    0xfff38393,  // 0x20  code
    0xfe039ce3,  // 0x24  code
    0x06400393,  // 0x28  code
    0x0002a503,  // 0x2c  code
    0x00a70733,  // 0x30  code
    0x00000593,  // 0x34  code
    0x0124de63,  // 0x38  code
    0x00e05c63,  // 0x3c  code
    0x00249613,  // 0x40  code
    0x00860633,  // 0x44  code
    0x00062583,  // 0x48  code
    0x00148493,  // 0x4c  code
    0xfff70713,  // 0x50  code
    0x00b32023,  // 0x54  code
    0xfff38393,  // 0x58  code
    0xfc0398e3,  // 0x5c  code
    0x021810f0,  // 0x60  PACKET  irf[0] = ADD SYSRGT, drf0, drf1
    0x02190773,  // 0x64  PACKET  irf[1] = NOP
    0x021a0773,  // 0x68  PACKET  irf[2] = NOP
    0x021b0773,  // 0x6c  PACKET  irf[3] = NOP
    0x021c0773,  // 0x70  PACKET  irf[4] = NOP
    0x021d0773,  // 0x74  PACKET  irf[5] = NOP
    0x021e0773,  // 0x78  PACKET  irf[6] = NOP
    0x021f0773,  // 0x7c  PACKET  irf[7] = NOP
    0x02003c00,  // 0x80  PACKET  drf[0] = fp16 1.0
    0x02014000,  // 0x84  PACKET  drf[1] = fp16 2.0
    0x02110001,  // 0x88  PACKET  config_reg_1: iter count = 1
    0x02108000,  // 0x8c  PACKET  config_reg_0: isz=0 | fetch_en  <- PE starts
};
const int PROGRAMMER_WORDS = sizeof(PROGRAMMER_PROGRAM) / sizeof(PROGRAMMER_PROGRAM[0]);

// ---- Program ROM 4: EVA program source (2x2) -----------------------------
// The EVA-faithful variant. Rather than replacing rdrv_w, the processor feeds
// it: it emits the program image on a stream and EVA's own driver buffers it
// and does the credit-gated replay. That is the role a host plays, so this
// program implements no protocol at all -- it writes PKTSRC_NPKT packets and
// halts. (Contrast PROGRAMMER_PROGRAM above, which has to prime, read credits
// and interleave bubbles because it *is* the driver.)
//
// One instance per west lane. Lane r carries node (r,0) then (r,1); on the west
// edge the packet's id field selects the COLUMN (axis[0] = col_id). Column 0 is
// programmed to send its result west, column 1 east, so all four PEs reach a
// boundary collector. Both lanes get the same image here because all four PEs
// run the same kernel; per-node programs would just mean per-lane ROMs.
// Generated by rvasm.py: eva_pktsrc_program(...). Verified at 2x2 on Allo's CPU
// simulator against the stock chip before being baked in.
const int PKTSRC_NPKT = 24;
const int PKTSRC_HALT_PC = 0x4c;
const ap_uint<32> PKTSRC_PROGRAM[] = {
    0x000082b7,  // 0x00  code
    0x01028293,  // 0x04  code
    0x00428313,  // 0x08  code
    0x04c00413,  // 0x0c  code
    0x00000493,  // 0x10  code
    0x01800913,  // 0x14  code
    0x00249613,  // 0x18  code
    0x00860633,  // 0x1c  code
    0x00062583,  // 0x20  code
    0x00b2a023,  // 0x24  code
    0x00148493,  // 0x28  code
    0xff2496e3,  // 0x2c  code
    0x03000913,  // 0x30  code
    0x00249613,  // 0x34  code
    0x00860633,  // 0x38  code
    0x00062583,  // 0x3c  code
    0x00b32023,  // 0x40  code
    0x00148493,  // 0x44  code
    0xff2496e3,  // 0x48  code
    0x021810e0,  // 0x4c  lane 0, packet  0
    0x02190773,  // 0x50  lane 0, packet  1
    0x021a0773,  // 0x54  lane 0, packet  2
    0x021b0773,  // 0x58  lane 0, packet  3
    0x021c0773,  // 0x5c  lane 0, packet  4
    0x021d0773,  // 0x60  lane 0, packet  5
    0x021e0773,  // 0x64  lane 0, packet  6
    0x021f0773,  // 0x68  lane 0, packet  7
    0x02003c00,  // 0x6c  lane 0, packet  8
    0x02014000,  // 0x70  lane 0, packet  9
    0x02110001,  // 0x74  lane 0, packet 10
    0x02108000,  // 0x78  lane 0, packet 11
    0x023810f0,  // 0x7c  lane 0, packet 12
    0x02390773,  // 0x80  lane 0, packet 13
    0x023a0773,  // 0x84  lane 0, packet 14
    0x023b0773,  // 0x88  lane 0, packet 15
    0x023c0773,  // 0x8c  lane 0, packet 16
    0x023d0773,  // 0x90  lane 0, packet 17
    0x023e0773,  // 0x94  lane 0, packet 18
    0x023f0773,  // 0x98  lane 0, packet 19
    0x02203c00,  // 0x9c  lane 0, packet 20
    0x02214000,  // 0xa0  lane 0, packet 21
    0x02310001,  // 0xa4  lane 0, packet 22
    0x02308000,  // 0xa8  lane 0, packet 23
    0x021810e0,  // 0xac  lane 1, packet  0
    0x02190773,  // 0xb0  lane 1, packet  1
    0x021a0773,  // 0xb4  lane 1, packet  2
    0x021b0773,  // 0xb8  lane 1, packet  3
    0x021c0773,  // 0xbc  lane 1, packet  4
    0x021d0773,  // 0xc0  lane 1, packet  5
    0x021e0773,  // 0xc4  lane 1, packet  6
    0x021f0773,  // 0xc8  lane 1, packet  7
    0x02003c00,  // 0xcc  lane 1, packet  8
    0x02014000,  // 0xd0  lane 1, packet  9
    0x02110001,  // 0xd4  lane 1, packet 10
    0x02108000,  // 0xd8  lane 1, packet 11
    0x023810f0,  // 0xdc  lane 1, packet 12
    0x02390773,  // 0xe0  lane 1, packet 13
    0x023a0773,  // 0xe4  lane 1, packet 14
    0x023b0773,  // 0xe8  lane 1, packet 15
    0x023c0773,  // 0xec  lane 1, packet 16
    0x023d0773,  // 0xf0  lane 1, packet 17
    0x023e0773,  // 0xf4  lane 1, packet 18
    0x023f0773,  // 0xf8  lane 1, packet 19
    0x02203c00,  // 0xfc  lane 1, packet 20
    0x02214000,  // 0x100  lane 1, packet 21
    0x02310001,  // 0x104  lane 1, packet 22
    0x02308000,  // 0x108  lane 1, packet 23
};
const int PKTSRC_WORDS = sizeof(PKTSRC_PROGRAM) / sizeof(PKTSRC_PROGRAM[0]);

// ---- Program ROM 6: the real workload, on a 2x2 grid ----------------------
// One processor, both west lanes. Node (i,j) holds W[i][j] of
//     W = [[1, 3], [5, 7]]
// so the two lanes carry DIFFERENT images -- which is the whole reason this top
// exists. Lane i carries node (i,0) then (i,1); on the west edge the packet id
// selects the column. cfg_itsz = 3, so each PE loops the 4-instruction kernel
// three times.
//
// Host supplies activations X[b,i] on west row i at PROG_CYCLES + 4*b, plus a
// valid-zero north seed. No START skew is needed: DATADRIVEN=1 stalls each PE
// until its operands are valid, so the skew emerges from the stalls.
// X = [[2,4],[1,3],[5,2]] -> out_s = [[22,16,15],[34,24,29]] (verified on the
// CPU simulator against the stock chip).
const int MMMSRC2_NPKT = 22;
const int MMMSRC2_HALT_PC = 0x4c;
const ap_uint<32> MMMSRC2_PROGRAM[] = {
    0x000082b7,  // 0x00  code
    0x01028293,  // 0x04  code
    0x00428313,  // 0x08  code
    0x04c00413,  // 0x0c  code
    0x00000493,  // 0x10  code
    0x01600913,  // 0x14  code
    0x00249613,  // 0x18  code
    0x00860633,  // 0x1c  code
    0x00062583,  // 0x20  code
    0x00b2a023,  // 0x24  code
    0x00148493,  // 0x28  code
    0xff2496e3,  // 0x2c  code
    0x02c00913,  // 0x30  code
    0x00249613,  // 0x34  code
    0x00860633,  // 0x38  code
    0x00062583,  // 0x3c  code
    0x00b32023,  // 0x40  code
    0x00148493,  // 0x44  code
    0xff2496e3,  // 0x48  code
    0x02180e13,  // 0x4c  lane 0, packet  0
    0x02191022,  // 0x50  lane 0, packet  1
    0x021a01f3,  // 0x54  lane 0, packet  2
    0x021bc2d0,  // 0x58  lane 0, packet  3
    0x021c0773,  // 0x5c  lane 0, packet  4
    0x021d0773,  // 0x60  lane 0, packet  5
    0x021e0773,  // 0x64  lane 0, packet  6
    0x021f0773,  // 0x68  lane 0, packet  7
    0x02003c00,  // 0x6c  lane 0, packet  8
    0x02110003,  // 0x70  lane 0, packet  9
    0x02108300,  // 0x74  lane 0, packet 10
    0x02380e13,  // 0x78  lane 0, packet 11
    0x02391022,  // 0x7c  lane 0, packet 12
    0x023a01f3,  // 0x80  lane 0, packet 13
    0x023bc2d0,  // 0x84  lane 0, packet 14
    0x023c0773,  // 0x88  lane 0, packet 15
    0x023d0773,  // 0x8c  lane 0, packet 16
    0x023e0773,  // 0x90  lane 0, packet 17
    0x023f0773,  // 0x94  lane 0, packet 18
    0x02204200,  // 0x98  lane 0, packet 19
    0x02310003,  // 0x9c  lane 0, packet 20
    0x02308300,  // 0xa0  lane 0, packet 21
    0x02180e13,  // 0xa4  lane 1, packet  0
    0x02191022,  // 0xa8  lane 1, packet  1
    0x021a01f3,  // 0xac  lane 1, packet  2
    0x021bc2d0,  // 0xb0  lane 1, packet  3
    0x021c0773,  // 0xb4  lane 1, packet  4
    0x021d0773,  // 0xb8  lane 1, packet  5
    0x021e0773,  // 0xbc  lane 1, packet  6
    0x021f0773,  // 0xc0  lane 1, packet  7
    0x02004500,  // 0xc4  lane 1, packet  8
    0x02110003,  // 0xc8  lane 1, packet  9
    0x02108300,  // 0xcc  lane 1, packet 10
    0x02380e13,  // 0xd0  lane 1, packet 11
    0x02391022,  // 0xd4  lane 1, packet 12
    0x023a01f3,  // 0xd8  lane 1, packet 13
    0x023bc2d0,  // 0xdc  lane 1, packet 14
    0x023c0773,  // 0xe0  lane 1, packet 15
    0x023d0773,  // 0xe4  lane 1, packet 16
    0x023e0773,  // 0xe8  lane 1, packet 17
    0x023f0773,  // 0xec  lane 1, packet 18
    0x02204700,  // 0xf0  lane 1, packet 19
    0x02310003,  // 0xf4  lane 1, packet 20
    0x02308300,  // 0xf8  lane 1, packet 21
};
const int MMMSRC2_WORDS = sizeof(MMMSRC2_PROGRAM) / sizeof(MMMSRC2_PROGRAM[0]);

// ---- Program ROM 5: the real workload -------------------------------------
// Everything above boots a PE to compute 1.0 + 2.0, which proves the plumbing
// and nothing else. This boots it to run EVA's golden weight-stationary MMM
// kernel -- the same four instructions eva_workloads.load_mmm_router uses --
// with a stationary weight of fp16 3.0 and cfg_itsz = 3, so the kernel loops
// three times out of irf[0..3].
//
//   I0  MOV  r1, SYSLFT          activation in from the west
//   I1  MULT r2, r0, r1          r0 = drf[0] = the stationary weight
//   I2  MOV  SYSRGT, r1          forward the activation east
//   I3  ADD  SYSBTM, r2, SYSTOP  accumulate with north, send south
//
// The processor supplies only the program and the weight. Activations are the
// host's job: they must arrive on the west systolic edge at
// PROG_CYCLES + 4*b (PROG_CYCLES = 16), with the north edge seeded valid-zero.
// With X = [2, 4, 1] the array returns [6, 12, 3] on out_s.
// Generated by rvasm.py: eva_pktsrc_program(eva_mmm_packets(0x4200, batch=3)),
// and verified against the chip's own golden result on Allo's CPU simulator.
const int MMMSRC_NPKT = 11;              // 8 IRF + 1 DRF + 2 config
const int MMMSRC_BATCH = 3;
const int MMMSRC_HALT_PC = 0x2c;
const ap_uint<32> MMMSRC_PROGRAM[] = {
    0x000082b7,  // 0x00  code
    0x01028293,  // 0x04  code
    0x02c00413,  // 0x08  code
    0x00000493,  // 0x0c  code
    0x00b00913,  // 0x10  code
    0x00249613,  // 0x14  code
    0x00860633,  // 0x18  code
    0x00062583,  // 0x1c  code
    0x00b2a023,  // 0x20  code
    0x00148493,  // 0x24  code
    0xff2496e3,  // 0x28  code
    0x02180e13,  // 0x2c  PACKET  irf[0] = MOV  r1, SYSLFT
    0x02191022,  // 0x30  PACKET  irf[1] = MULT r2, r0, r1
    0x021a01f3,  // 0x34  PACKET  irf[2] = MOV  SYSRGT, r1
    0x021bc2d0,  // 0x38  PACKET  irf[3] = ADD  SYSBTM, r2, SYSTOP
    0x021c0773,  // 0x3c  PACKET  irf[4] = NOP
    0x021d0773,  // 0x40  PACKET  irf[5] = NOP
    0x021e0773,  // 0x44  PACKET  irf[6] = NOP
    0x021f0773,  // 0x48  PACKET  irf[7] = NOP
    0x02004200,  // 0x4c  PACKET  drf[0] = fp16 3.0   (stationary weight)
    0x02110003,  // 0x50  PACKET  config_reg_1 = iter count 3
    0x02108300,  // 0x54  PACKET  config_reg_0 = isz 3 | fetch_en  <- PE starts
};
const int MMMSRC_WORDS = sizeof(MMMSRC_PROGRAM) / sizeof(MMMSRC_PROGRAM[0]);

template<int N>
struct BitPatImpl {
  const char (&pat)[N];
  inline bool operator==(const ap_uint<N-2>& v) const {
#pragma HLS INLINE
#pragma HLS ARRAY_PARTITION variable=pat dim=1 type=complete
    bool result = true;
    for (int i = 0; i < N - 2; i++) {
#pragma HLS UNROLL
      result = result && (pat[i+1] == '?' || v[N-3-i] == (pat[i+1] == '1' ? 1 : 0));
    }
    return result;
  }
};

template<int N>
constexpr BitPatImpl<N> BitPat(const char (&pat)[N]) {
  return BitPatImpl<N>{ pat };
}

// ロード・ストア
constexpr auto LW      = BitPat("b?????????????????010?????0000011");
constexpr auto SW      = BitPat("b?????????????????010?????0100011");

// 加算
constexpr auto ADD     = BitPat("b0000000??????????000?????0110011");
constexpr auto ADDI    = BitPat("b?????????????????000?????0010011");

// 減算
constexpr auto SUB     = BitPat("b0100000??????????000?????0110011");

// 論理演算
constexpr auto AND     = BitPat("b0000000??????????111?????0110011");
constexpr auto OR      = BitPat("b0000000??????????110?????0110011");
constexpr auto XOR     = BitPat("b0000000??????????100?????0110011");
constexpr auto ANDI    = BitPat("b?????????????????111?????0010011");
constexpr auto ORI     = BitPat("b?????????????????110?????0010011");
constexpr auto XORI    = BitPat("b?????????????????100?????0010011");

// シフト
constexpr auto SLL     = BitPat("b0000000??????????001?????0110011");
constexpr auto SRL     = BitPat("b0000000??????????101?????0110011");
constexpr auto SRA     = BitPat("b0100000??????????101?????0110011");
constexpr auto SLLI    = BitPat("b0000000??????????001?????0010011");
constexpr auto SRLI    = BitPat("b0000000??????????101?????0010011");
constexpr auto SRAI    = BitPat("b0100000??????????101?????0010011");

// 比較
constexpr auto SLT     = BitPat("b0000000??????????010?????0110011");
constexpr auto SLTU    = BitPat("b0000000??????????011?????0110011");
constexpr auto SLTI    = BitPat("b?????????????????010?????0010011");
constexpr auto SLTIU   = BitPat("b?????????????????011?????0010011");

// 条件分岐
constexpr auto BEQ     = BitPat("b?????????????????000?????1100011");
constexpr auto BNE     = BitPat("b?????????????????001?????1100011");
constexpr auto BLT     = BitPat("b?????????????????100?????1100011");
constexpr auto BGE     = BitPat("b?????????????????101?????1100011");
constexpr auto BLTU    = BitPat("b?????????????????110?????1100011");
constexpr auto BGEU    = BitPat("b?????????????????111?????1100011");

// ジャンプ
constexpr auto JAL     = BitPat("b?????????????????????????1101111");
constexpr auto JALR    = BitPat("b?????????????????000?????1100111");

// 即値ロード
constexpr auto LUI     = BitPat("b?????????????????????????0110111");
constexpr auto AUIPC   = BitPat("b?????????????????????????0010111");

// CSR
constexpr auto CSRRW   = BitPat("b?????????????????001?????1110011");
constexpr auto CSRRWI  = BitPat("b?????????????????101?????1110011");
constexpr auto CSRRS   = BitPat("b?????????????????010?????1110011");
constexpr auto CSRRSI  = BitPat("b?????????????????110?????1110011");
constexpr auto CSRRC   = BitPat("b?????????????????011?????1110011");
constexpr auto CSRRCI  = BitPat("b?????????????????111?????1110011");

// 例外
constexpr auto ECALL   = BitPat("b00000000000000000000000001110011");

constexpr int ALU_X      =  0;
constexpr int ALU_ADD    =  1;
constexpr int ALU_SUB    =  2;
constexpr int ALU_AND    =  3;
constexpr int ALU_OR     =  4;
constexpr int ALU_XOR    =  5;
constexpr int ALU_SLL    =  6;
constexpr int ALU_SRL    =  7;
constexpr int ALU_SRA    =  8;
constexpr int ALU_SLT    =  9;
constexpr int ALU_SLTU   = 10;
constexpr int BR_BEQ     = 11;
constexpr int BR_BNE     = 12;
constexpr int BR_BLT     = 13;
constexpr int BR_BGE     = 14;
constexpr int BR_BLTU    = 15;
constexpr int BR_BGEU    = 16;
constexpr int ALU_JALR   = 17;
constexpr int ALU_COPY1  = 18;

constexpr int OP1_RS1    = 0;
constexpr int OP1_PC     = 1;
constexpr int OP1_X      = 2;
constexpr int OP1_IMZ    = 3;

constexpr int OP2_X      = 0;
constexpr int OP2_RS2    = 1;
constexpr int OP2_IMI    = 2;
constexpr int OP2_IMS    = 3;
constexpr int OP2_IMJ    = 4;
constexpr int OP2_IMU    = 5;

constexpr int MEN_X      = 0;
constexpr int MEN_S      = 1;

constexpr int REN_X      = 0;
constexpr int REN_S      = 1;

constexpr int WB_X       = 0;
constexpr int WB_ALU     = 0;
constexpr int WB_MEM     = 1;
constexpr int WB_PC      = 2;
constexpr int WB_CSR     = 3;

constexpr int CSR_X      = 0;
constexpr int CSR_W      = 1;
constexpr int CSR_S      = 2;
constexpr int CSR_C      = 3;
constexpr int CSR_E      = 4;

// The processor itself. All three tops below are this one core running a
// different program ROM; only the MMIO addresses a program touches decide which
// stream ports it actually uses.
//
// ---- Port bundles ---------------------------------------------------------
// One per IP role. rv_core is templated on these rather than taking every port
// it might need, because Vitis rejects a stream port that is never read or
// written ("Illegal connection is found on FIFO pin ... most likely due to a
// stream that is either never read or never written"). Passing dummy streams
// for the ports a role does not use therefore fails RTL generation; giving each
// role exactly its own ports avoids the problem entirely, and the address
// dispatch below collapses at compile time.

// vadd: one int32 stream in, one out.
struct VaddPorts {
  hls::stream<int32_t>& sin;
  hls::stream<int32_t>& sout;
  bool is_mmio_load(ap_uint<32> a) const { return a == MMIO_IN; }
  bool is_mmio_store(ap_uint<32> a) const { return a == MMIO_OUT; }
  ap_uint<32> load(ap_uint<32> a) { return (ap_uint<32>) sin.read(); }
  void store(ap_uint<32> a, ap_uint<32> v) { sout.write((int32_t) v); }
};

// EVA east collector: systolic words in, credits out, raw words forwarded on.
struct CollectorPorts {
  hls::stream<sys_word_t>& sys_in;
  hls::stream<int32_t>&    scr_out;
  hls::stream<sys_word_t>& res_out;
  bool is_mmio_load(ap_uint<32> a) const { return a == MMIO_IN17; }
  bool is_mmio_store(ap_uint<32> a) const {
    return a == MMIO_OUT || a == MMIO_OUT17;
  }
  ap_uint<32> load(ap_uint<32> a) { return (ap_uint<32>) sys_in.read(); }
  void store(ap_uint<32> a, ap_uint<32> v) {
    if (a == MMIO_OUT) scr_out.write((int32_t) v);
    else               res_out.write((sys_word_t) v);
  }
};

// EVA program source: router packets out, nothing in. The only bundle with no
// input port -- the processor is a pure producer here, so the core never
// blocks on a load.
struct PktSrcPorts {
  hls::stream<pkt_t>& rtr_out;
  bool is_mmio_load(ap_uint<32> a) const { return false; }
  bool is_mmio_store(ap_uint<32> a) const { return a == MMIO_OUT26; }
  ap_uint<32> load(ap_uint<32> a) { return 0; }
  void store(ap_uint<32> a, ap_uint<32> v) { rtr_out.write((pkt_t) v); }
};

// EVA program source for TWO west lanes, from one processor.
//
// meta_for(0, M) instantiates the same top M times, so M instances all carry
// the same ROM -- fine while every PE runs the same program, useless once each
// node needs its own stationary weight. One processor driving both lanes fixes
// that: the address selects the lane.
struct PktSrc2Ports {
  hls::stream<pkt_t>& rtr_out0;
  hls::stream<pkt_t>& rtr_out1;
  bool is_mmio_load(ap_uint<32> a) const { return false; }
  bool is_mmio_store(ap_uint<32> a) const {
    return a == MMIO_OUT26 || a == MMIO_OUT26B;
  }
  ap_uint<32> load(ap_uint<32> a) { return 0; }
  void store(ap_uint<32> a, ap_uint<32> v) {
    if (a == MMIO_OUT26) rtr_out0.write((pkt_t) v);
    else                 rtr_out1.write((pkt_t) v);
  }
};

// EVA PE programmer: link credits in, router packets out.
struct ProgrammerPorts {
  hls::stream<int32_t>& cr_in;
  hls::stream<pkt_t>&   rtr_out;
  bool is_mmio_load(ap_uint<32> a) const { return a == MMIO_IN; }
  bool is_mmio_store(ap_uint<32> a) const { return a == MMIO_OUT26; }
  ap_uint<32> load(ap_uint<32> a) { return (ap_uint<32>) cr_in.read(); }
  void store(ap_uint<32> a, ap_uint<32> v) { rtr_out.write((pkt_t) v); }
};

template <typename Ports>
static void rv_core(
  Ports&             io,
  const ap_uint<32>* prog,
  int                prog_words,
  int                halt_pc
) {

  ap_uint<8> local_mem[MEM_SIZE];
#pragma HLS ARRAY_RESHAPE variable=local_mem type=cyclic factor=4 dim=1
  ap_uint<32> regfile[32];
  ap_uint<32> csr_regfile[4096];
  ap_uint<32> pc_reg = 0;

clear_mem:
  for (int i = 0; i < MEM_SIZE; i++) {
    local_mem[i] = 0;
  }

// Load the program ROM into instruction memory, little-endian.
load_program:
  for (int i = 0; i < prog_words; i++) {
    local_mem[i * 4 + 0] = prog[i]( 7,  0);
    local_mem[i * 4 + 1] = prog[i](15,  8);
    local_mem[i * 4 + 2] = prog[i](23, 16);
    local_mem[i * 4 + 3] = prog[i](31, 24);
  }

clear_regfile:
  for (int i = 0; i < 32; i++) {
    regfile[i] = 0;
  }

clear_csr_regfile:
  for (int i = 0; i < 4096; i++) {
    csr_regfile[i] = 0;
  }

core:
  while (true) {
    // Test exit condition
    if (pc_reg == halt_pc) break;

    ap_uint<32> inst;
    inst( 7,  0) = (ap_uint<8>) local_mem[pc_reg + 0];
    inst(15,  8) = (ap_uint<8>) local_mem[pc_reg + 1];
    inst(23, 16) = (ap_uint<8>) local_mem[pc_reg + 2];
    inst(31, 24) = (ap_uint<8>) local_mem[pc_reg + 3];

    ap_uint<5> rs1_addr = inst(19, 15);
    ap_uint<5> rs2_addr = inst(24, 20);
    ap_uint<5> wb_addr = inst(11, 7);

    ap_uint<32> rs1_data = rs1_addr == 0 ? ap_uint<32>(0) : regfile[rs1_addr];
    ap_uint<32> rs2_data = rs2_addr == 0 ? ap_uint<32>(0) : regfile[rs2_addr];

    ap_int<12>  imm_i = inst(31, 20);
    ap_int<12>  imm_s = (inst(31, 25), inst(11, 7));
    ap_int<12>  imm_b = (inst[31], inst[7], inst(30, 25), inst(11, 8));
    ap_int<12>  imm_j = (inst[31], inst(19,12), inst[20], inst(30, 21));
    ap_uint<20> imm_u = inst(31, 12);
    ap_uint<5>  imm_z = inst(19, 15);

    ap_int<13> imm_b_sext = (imm_b << 1);
    ap_int<13> imm_j_sext = (imm_j << 1);
    ap_uint<32> imm_u_shifted = ap_uint<32>(imm_u) << 12;

    int exe_fun = ALU_X, op1_sel = OP1_RS1, op2_sel = OP2_RS2, mem_wen = MEN_X;
    int rf_wen = REN_X, wb_sel = WB_X, csr_cmd = CSR_X;
#define DECODE_INST(x, alu, op1, op2, men, ren, wb, csr) \
    if (x == inst) { exe_fun = alu; op1_sel = op1; \
      op2_sel = op2; mem_wen = men; rf_wen = ren; wb_sel = wb; csr_cmd = csr; }
    DECODE_INST(LW    , ALU_ADD  , OP1_RS1, OP2_IMI, MEN_X, REN_S, WB_MEM, CSR_X)
    DECODE_INST(SW    , ALU_ADD  , OP1_RS1, OP2_IMS, MEN_S, REN_X, WB_X  , CSR_X)
    DECODE_INST(ADD   , ALU_ADD  , OP1_RS1, OP2_RS2, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(ADDI  , ALU_ADD  , OP1_RS1, OP2_IMI, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(SUB   , ALU_SUB  , OP1_RS1, OP2_RS2, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(AND   , ALU_AND  , OP1_RS1, OP2_RS2, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(OR    , ALU_OR   , OP1_RS1, OP2_RS2, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(XOR   , ALU_XOR  , OP1_RS1, OP2_RS2, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(ANDI  , ALU_AND  , OP1_RS1, OP2_IMI, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(ORI   , ALU_OR   , OP1_RS1, OP2_IMI, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(XORI  , ALU_XOR  , OP1_RS1, OP2_IMI, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(SLL   , ALU_SLL  , OP1_RS1, OP2_RS2, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(SRL   , ALU_SRL  , OP1_RS1, OP2_RS2, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(SRA   , ALU_SRA  , OP1_RS1, OP2_RS2, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(SLLI  , ALU_SLL  , OP1_RS1, OP2_IMI, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(SRLI  , ALU_SRL  , OP1_RS1, OP2_IMI, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(SRAI  , ALU_SRA  , OP1_RS1, OP2_IMI, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(SLT   , ALU_SLT  , OP1_RS1, OP2_RS2, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(SLTU  , ALU_SLTU , OP1_RS1, OP2_RS2, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(SLTI  , ALU_SLT  , OP1_RS1, OP2_IMI, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(SLTIU , ALU_SLTU , OP1_RS1, OP2_IMI, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(BEQ   , BR_BEQ   , OP1_RS1, OP2_RS2, MEN_X, REN_X, WB_X  , CSR_X)
    DECODE_INST(BNE   , BR_BNE   , OP1_RS1, OP2_RS2, MEN_X, REN_X, WB_X  , CSR_X)
    DECODE_INST(BGE   , BR_BGE   , OP1_RS1, OP2_RS2, MEN_X, REN_X, WB_X  , CSR_X)
    DECODE_INST(BGEU  , BR_BGEU  , OP1_RS1, OP2_RS2, MEN_X, REN_X, WB_X  , CSR_X)
    DECODE_INST(BLT   , BR_BLT   , OP1_RS1, OP2_RS2, MEN_X, REN_X, WB_X  , CSR_X)
    DECODE_INST(BLTU  , BR_BLTU  , OP1_RS1, OP2_RS2, MEN_X, REN_X, WB_X  , CSR_X)
    DECODE_INST(JAL   , ALU_ADD  , OP1_PC , OP2_IMJ, MEN_X, REN_S, WB_PC , CSR_X)
    DECODE_INST(JALR  , ALU_JALR , OP1_RS1, OP2_IMI, MEN_X, REN_S, WB_PC , CSR_X)
    DECODE_INST(LUI   , ALU_ADD  , OP1_X  , OP2_IMU, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(AUIPC , ALU_ADD  , OP1_PC , OP2_IMU, MEN_X, REN_S, WB_ALU, CSR_X)
    DECODE_INST(CSRRW , ALU_COPY1, OP1_RS1, OP2_X  , MEN_X, REN_S, WB_CSR, CSR_W)
    DECODE_INST(CSRRWI, ALU_COPY1, OP1_IMZ, OP2_X  , MEN_X, REN_S, WB_CSR, CSR_W)
    DECODE_INST(CSRRS , ALU_COPY1, OP1_RS1, OP2_X  , MEN_X, REN_S, WB_CSR, CSR_S)
    DECODE_INST(CSRRSI, ALU_COPY1, OP1_IMZ, OP2_X  , MEN_X, REN_S, WB_CSR, CSR_S)
    DECODE_INST(CSRRC , ALU_COPY1, OP1_RS1, OP2_X  , MEN_X, REN_S, WB_CSR, CSR_C)
    DECODE_INST(CSRRCI, ALU_COPY1, OP1_IMZ, OP2_X  , MEN_X, REN_S, WB_CSR, CSR_C)
    DECODE_INST(ECALL , ALU_X    , OP1_X  , OP2_X  , MEN_X, REN_X, WB_X  , CSR_E)
#undef DECODE_INST

    ap_uint<32> op1_data = 0;
    if (op1_sel == OP1_RS1) op1_data = rs1_data;
    if (op1_sel == OP1_PC ) op1_data = pc_reg  ;
    if (op1_sel == OP1_IMZ) op1_data = imm_z   ;

    ap_uint<32> op2_data = 0;
    if (op2_sel == OP2_RS2) op2_data = rs2_data     ;
    if (op2_sel == OP2_IMI) op2_data = imm_i        ;
    if (op2_sel == OP2_IMS) op2_data = imm_s        ;
    if (op2_sel == OP2_IMJ) op2_data = imm_j_sext   ;
    if (op2_sel == OP2_IMU) op2_data = imm_u_shifted;

    // Execute stage
    ap_uint<32> alu_out = 0;
    if (exe_fun == ALU_ADD  ) alu_out = op1_data + op2_data;
    if (exe_fun == ALU_SUB  ) alu_out = op1_data - op2_data;
    if (exe_fun == ALU_AND  ) alu_out = op1_data & op2_data;
    if (exe_fun == ALU_OR   ) alu_out = op1_data | op2_data;
    if (exe_fun == ALU_XOR  ) alu_out = op1_data ^ op2_data;
    if (exe_fun == ALU_SLL  ) alu_out = op1_data << op2_data(4, 0);
    if (exe_fun == ALU_SRL  ) alu_out = op1_data >> op2_data(4, 0);
    if (exe_fun == ALU_SRA  ) alu_out = ap_int<32>(op1_data) >> op2_data(4, 0);
    if (exe_fun == ALU_SLT  ) alu_out = ap_int<32>(op1_data) < ap_int<32>(op2_data);
    if (exe_fun == ALU_SLTU ) alu_out = op1_data < op2_data;
    if (exe_fun == ALU_JALR ) alu_out = (op1_data + op2_data) & ~1;
    if (exe_fun == ALU_COPY1) alu_out = op1_data;

    // Branch
    bool br_flg = false;
    ap_uint<32> br_target = pc_reg + imm_b_sext;
    if (exe_fun == BR_BEQ ) br_flg =  (op1_data == op2_data);
    if (exe_fun == BR_BNE ) br_flg = !(op1_data == op2_data);
    if (exe_fun == BR_BLT ) br_flg =  (ap_int<32>(op1_data) < ap_int<32>(op2_data));
    if (exe_fun == BR_BGE ) br_flg = !(ap_int<32>(op1_data) < ap_int<32>(op2_data));
    if (exe_fun == BR_BLTU) br_flg =  (op1_data < op2_data);
    if (exe_fun == BR_BGEU) br_flg = !(op1_data < op2_data);

    // CSR
    ap_uint<12> csr_addr = csr_cmd == CSR_E ? ap_uint<12>(0x342) : inst(31, 20);
    ap_uint<32> csr_rdata = csr_regfile[csr_addr];
    ap_uint<32> csr_wdata = 0;
    if (csr_cmd == CSR_W) csr_wdata = op1_data;
    if (csr_cmd == CSR_S) csr_wdata = csr_rdata |  op1_data;
    if (csr_cmd == CSR_C) csr_wdata = csr_rdata & ~op1_data;
    if (csr_cmd == CSR_E) csr_wdata = 11;

    if (csr_cmd > 0) csr_regfile[csr_addr] = csr_wdata;

    // Writeback stage
    ap_uint<32> wb_data = alu_out;

    if (mem_wen == MEN_S) {
      // A store to an MMIO address is a FIFO write, not a memory write.
      if (io.is_mmio_store(alu_out)) {
        io.store(alu_out, rs2_data);
      } else {
        local_mem[alu_out + 0] = rs2_data( 7,  0);
        local_mem[alu_out + 1] = rs2_data(15,  8);
        local_mem[alu_out + 2] = rs2_data(23, 16);
        local_mem[alu_out + 3] = rs2_data(31, 24);
      }
    } else if (wb_sel == WB_MEM) {
      // A load from an MMIO address is a blocking FIFO read. Blocking is what
      // makes the core a well-behaved dataflow citizen: it stalls until a
      // producer kernel supplies a value, as Allo's own stream.get() does.
      if (io.is_mmio_load(alu_out)) {
        wb_data = io.load(alu_out);
      } else {
        wb_data( 7,  0) = (ap_uint<8>) local_mem[alu_out + 0];
        wb_data(15,  8) = (ap_uint<8>) local_mem[alu_out + 1];
        wb_data(23, 16) = (ap_uint<8>) local_mem[alu_out + 2];
        wb_data(31, 24) = (ap_uint<8>) local_mem[alu_out + 3];
      }
    } else if (wb_sel == WB_PC) {
      wb_data = pc_reg + 4;
    } else if (wb_sel == WB_CSR) {
      wb_data = csr_rdata;
    }

    if (rf_wen == REN_S) {
      regfile[wb_addr] = wb_data;
    }

#ifndef __SYNTHESIS__
    std::cout << "===========" << std::endl;
    std::cout << "pc_reg   = " << std::setw(16) << std::hex << pc_reg << std::endl;
    std::cout << "inst     = " << std::setw(16) << std::hex << inst;
#define PRINT_INST(x) if (x == inst) std::cout << "  " << #x << std::endl; else
    PRINT_INST(LW    )
    PRINT_INST(SW    )
    PRINT_INST(ADD   )
    PRINT_INST(ADDI  )
    PRINT_INST(SUB   )
    PRINT_INST(AND   )
    PRINT_INST(OR    )
    PRINT_INST(XOR   )
    PRINT_INST(ANDI  )
    PRINT_INST(ORI   )
    PRINT_INST(XORI  )
    PRINT_INST(SLL   )
    PRINT_INST(SRL   )
    PRINT_INST(SRA   )
    PRINT_INST(SLLI  )
    PRINT_INST(SRLI  )
    PRINT_INST(SRAI  )
    PRINT_INST(SLT   )
    PRINT_INST(SLTU  )
    PRINT_INST(SLTI  )
    PRINT_INST(SLTIU )
    PRINT_INST(BEQ   )
    PRINT_INST(BNE   )
    PRINT_INST(BGE   )
    PRINT_INST(BGEU  )
    PRINT_INST(BLT   )
    PRINT_INST(BLTU  )
    PRINT_INST(JAL   )
    PRINT_INST(JALR  )
    PRINT_INST(LUI   )
    PRINT_INST(AUIPC )
    PRINT_INST(CSRRW )
    PRINT_INST(CSRRWI)
    PRINT_INST(CSRRS )
    PRINT_INST(CSRRSI)
    PRINT_INST(CSRRC )
    PRINT_INST(CSRRCI)
    PRINT_INST(ECALL )
    std::cout << "  unimpl" << std::endl;
#undef PRINT_INST

    std::cout << "rs1_addr = " << std::dec << rs1_addr << std::endl;
    std::cout << "rs2_addr = " << std::dec << rs2_addr << std::endl;
    std::cout << "rs1_data = " << std::hex << rs1_data << std::endl;
    std::cout << "rs2_data = " << std::hex << rs2_data << std::endl;
    std::cout << "alu_out  = " << std::hex << alu_out << std::endl;
    std::cout << "wb_addr  = " << std::dec << wb_addr << std::endl;
    std::cout << "wb_data  = " << std::hex << wb_data << std::endl;
#endif

    if (br_flg) {
      pc_reg = br_target;
    } else if (JAL == inst || JALR == inst) {
      pc_reg = alu_out;
    } else if (ECALL == inst) {
      pc_reg = csr_regfile[0x305];
    } else {
      pc_reg = pc_reg + 4;
    }
  }

}

extern "C" {

// Top 1 -- the first integration test: 32 stream-fed additions, computed by
// RV32I machine code. Uses only the int32 ports.
void rv_stream_ip(
  hls::stream<int32_t>& sin,
  hls::stream<int32_t>& sout
) {
  VaddPorts io = {sin, sout};
  rv_core(io, PROGRAM, PROGRAM_WORDS, HALT_PC);
}

// Top 2 -- the EVA east collector. Replaces the col_e kernel at the array's
// east edge: consumes systolic words, returns one credit per valid word, and
// forwards every raw word to a drain kernel that does the fp16 unpack.
void rv_eva_collector(
  hls::stream<sys_word_t>& sys_in,
  hls::stream<int32_t>&    scr_out,
  hls::stream<sys_word_t>& res_out
) {
  CollectorPorts io = {sys_in, scr_out, res_out};
  rv_core(io, COLLECTOR_PROGRAM, COLLECTOR_WORDS, COLLECTOR_HALT_PC);
}

// Top 3 -- the EVA PE programmer. Replaces the rdrv_w kernel at the array's
// west edge: takes link credits in, and injects the router packets that load
// the PE's instruction register file, its operands, and finally fetch_en. The
// PE then runs the program the processor gave it.
void rv_eva_programmer(
  hls::stream<int32_t>& cr_in,
  hls::stream<pkt_t>&   rtr_out
) {
  ProgrammerPorts io = {cr_in, rtr_out};
  rv_core(io, PROGRAMMER_PROGRAM, PROGRAMMER_WORDS, PROGRAMMER_HALT_PC);
}

// Top 4 -- the EVA program source. Feeds EVA's own rdrv_w kernel rather than
// replacing it: emits the PE program image on a stream, and the driver buffers
// it into a local array and does the credit-gated replay. One instance per west
// lane. This is the EVA-faithful arrangement -- the processor produces the
// program, the array keeps its own timing logic.
void rv_eva_pktsrc(
  hls::stream<pkt_t>& rtr_out0,
  hls::stream<pkt_t>& rtr_out1
) {
  PktSrc2Ports io = {rtr_out0, rtr_out1};
  rv_core(io, PKTSRC_PROGRAM, PKTSRC_WORDS, PKTSRC_HALT_PC);
}

// Top 6 -- the real workload on a 2x2 grid. Both lanes from one processor,
// carrying different stationary weights per node.
void rv_eva_mmm_src_2x2(
  hls::stream<pkt_t>& rtr_out0,
  hls::stream<pkt_t>& rtr_out1
) {
  PktSrc2Ports io = {rtr_out0, rtr_out1};
  rv_core(io, MMMSRC2_PROGRAM, MMMSRC2_WORDS, MMMSRC2_HALT_PC);
}

// Top 5 -- the real workload. Same role as rv_eva_pktsrc, different ROM: this
// one boots the PE to run EVA's golden weight-stationary MMM kernel rather than
// a single add, so the array does actual arithmetic on streamed activations.
void rv_eva_mmm_src(
  hls::stream<pkt_t>& rtr_out
) {
  PktSrcPorts io = {rtr_out};
  rv_core(io, MMMSRC_PROGRAM, MMMSRC_WORDS, MMMSRC_HALT_PC);
}

} // extern "C"
