// Generated by gen_eva_program.py --header. Do not edit.
#ifndef __EVA_PROGRAM__H
#define __EVA_PROGRAM__H

static const unsigned EVA_PROGRAM_WORDS = 26;
static const unsigned EVA_PROGRAM_NPKT  = 11;
static const unsigned EVA_PROGRAM[] = {
    0x000322b7u, 0x03c00413u, 0x00000493u, 0x00b00913u,
    0x00249613u, 0x00860633u, 0x00062583u, 0x00b2a023u,
    0x00148493u, 0xff2496e3u, 0x00000013u, 0x00000013u,
    0x00000013u, 0x00000013u, 0x0000006fu, 0x02180e13u,
    0x02191022u, 0x021a01f3u, 0x021bc2d0u, 0x021c0773u,
    0x021d0773u, 0x021e0773u, 0x021f0773u, 0x02004200u,
    0x02110003u, 0x02108300u,
};

#endif
