#!/usr/bin/env python3
"""Generate an EVA boot program for DRIM4HLS: stores packets to MMIO_BASE.

The Vitis processor (ip/rv_stream_ip.cpp, ROM 5) does exactly this, but carries
its program and packet table in a ROM baked into the design. DRIM4HLS fetches
over a channel instead, so the same image is written to a .mem file that
top.cpp's loader puts into BOTH imem and dmem -- which is why the packet table
can simply follow the code at the same offsets.

    python gen_eva_program.py > eva_boot.mem
"""
import sys, os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "ip"))
from rvasm import LUI, ADDI, SLLI, ADD, LW, SW, BNE, eva_mmm_packets

DCACHE_SIZE = 51200           # must match defines.h
MMIO_BASE_BYTES = DCACHE_SIZE * 4   # 0x32000 -- word address MMIO_BASE
JAL_SELF = 0x0000006F         # decode.h treats this as end-of-program

TWO_LANE = "--2x2" in sys.argv

if TWO_LANE:
    # 2x2: node (i,j) holds W[i][j] of W = [[1,3],[5,7]], matching tb_top.cpp's
    # TARGET_MMM2X2. Lane i carries node (i,0) then (i,1); on the west edge the
    # packet's id field selects the COLUMN, so each lane is two boot sequences
    # concatenated with different weights and different ids.
    FP16 = {1.0: 0x3C00, 3.0: 0x4200, 5.0: 0x4500, 7.0: 0x4700}
    W = [[1.0, 3.0], [5.0, 7.0]]
    lane0 = (eva_mmm_packets(FP16[W[0][0]], batch=3, ident=0) +
             eva_mmm_packets(FP16[W[0][1]], batch=3, ident=1))
    lane1 = (eva_mmm_packets(FP16[W[1][0]], batch=3, ident=0) +
             eva_mmm_packets(FP16[W[1][1]], batch=3, ident=1))
    assert len(lane0) == len(lane1), "lanes must carry equal-length images"
    packets = lane0 + lane1
    NPKT_LANE = len(lane0)
else:
    # A 1x1 MMM: one PE holding a stationary weight, batch 3. Weight 3.0 (fp16
    # 0x4200) matches tb_top.cpp's TARGET_MMM1X1, so the expected result is the
    # already-verified out_s = [6, 12, 3] for X = [2, 4, 1].
    packets = eva_mmm_packets(0x4200, batch=3)
    NPKT_LANE = len(packets)

if TWO_LANE:
    # One processor, both west lanes -- the same structure as rvasm's
    # eva_pktsrc2_program. The index register is NOT reset between the loops:
    # the two images sit back to back in the table, so raising the bound to 2n
    # and falling through walks the second one. The store address picks the
    # lane: MMIO_BASE -> lane 0, MMIO_BASE+1 -> lane 1.
    n = NPKT_LANE
    code = [
        LUI ("t0", MMIO_BASE_BYTES >> 12),   # t0 = 0x32000, lane 0
        ADDI("t1", "t0", 4),                 # t1 = 0x32004, lane 1
        ADDI("s0", "x0", 0),                 # patched: table offset
        ADDI("s1", "x0", 0),                 # idx = 0
        ADDI("s2", "x0", n),                 # bound = n
        SLLI("a2", "s1", 2),                 # lane0: a2 = idx*4
        ADD ("a2", "a2", "s0"),
        LW  ("a1", "a2", 0),
        SW  ("a1", "t0", 0),                 # -> lane 0
        ADDI("s1", "s1", 1),
        BNE ("s1", "s2", (4 * 5) - (4 * 10)),
        ADDI("s2", "x0", 2 * n),             # bound = 2n, fall through
        SLLI("a2", "s1", 2),                 # lane1: same index register
        ADD ("a2", "a2", "s0"),
        LW  ("a1", "a2", 0),
        SW  ("a1", "t1", 0),                 # -> lane 1
        ADDI("s1", "s1", 1),
        BNE ("s1", "s2", (4 * 12) - (4 * 17)),
    ]
else:
    code = [
        LUI ("t0", MMIO_BASE_BYTES >> 12),   # t0 = 0x32000 (low 12 bits zero)
        ADDI("s0", "x0", 0),                 # patched below: table offset
        ADDI("s1", "x0", 0),                 # idx = 0
        ADDI("s2", "x0", len(packets)),      # npkts
        SLLI("a2", "s1", 2),                 # loop: a2 = idx*4
        ADD ("a2", "a2", "s0"),              # a2 = &table[idx]
        LW  ("a1", "a2", 0),                 # pkt = dmem[table + idx]
        SW  ("a1", "t0", 0),                 # mmio_out.Push(pkt)
        ADDI("s1", "s1", 1),
        BNE ("s1", "s2", (4 * 4) - (4 * 9)), # back to the SLLI (word 4)
    ]
code += [ADDI(0, 0, 0)] * 4              # drain NOPs before the halt
code += [JAL_SELF]
table_off = 4 * len(code)                # the table follows the code
code[2 if TWO_LANE else 1] = ADDI("s0", "x0", table_off)

image = code + list(packets)

if "--header" in sys.argv:
    # Baked into the design, the way the Vitis processor carries its ROM. The
    # wrapper copies this into imem AND dmem: the code fetches from one and the
    # packet table is read from the other, at the same offsets.
    print("// Generated by gen_eva_program.py --header. Do not edit.")
    print("#ifndef __EVA_PROGRAM__H\n#define __EVA_PROGRAM__H\n")
    print("static const unsigned EVA_PROGRAM_WORDS = %d;" % len(image))
    print("static const unsigned EVA_PROGRAM_NPKT  = %d;" % len(packets))
    print("static const unsigned EVA_PROGRAM[] = {")
    for i in range(0, len(image), 4):
        row = ", ".join("0x%08xu" % (w & 0xFFFFFFFF) for w in image[i:i + 4])
        print("    " + row + ",")
    print("};\n\n#endif")
else:
    for i, w in enumerate(image):
        print("0x%x 0x%08x" % (i * 4, w & 0xFFFFFFFF))
