# Catapult synthesis of the EVA chip AS EMITTED BY ALLO's SystemC backend.
#
# This is a different question from synthesising DRIM4HLS: that is hand-written
# SystemC designed for Catapult, whereas this is generated output, and nothing
# so far establishes that it is synthesisable at all.
#
# `tb` and sc_main live in the same generated file and cannot be -exclude'd
# separately, so the design is named explicitly by DESIGN_HIERARCHY instead --
# everything reachable from `top`, and nothing else.
set HERE [file normalize [file dirname [info script]]]
options set Input/CppStandard c++11
options set Input/SearchPath "$HERE" -append

project new -name evachip_synth
solution file add "$HERE/gen.cpp" -type C++
go analyze

directive set -DESIGN_HIERARCHY { top \
    node_0_0 \
    drv_w_0 drv_e_0 drv_n_0 drv_s_0 \
    col_w_0 col_e_0 col_n_0 col_s_0 \
    rdrv_w_0 rdrv_e_0 rdrv_n_0 rdrv_s_0 \
    rclc_w_0 rclc_e_0 rclc_n_0 rclc_s_0 }
go compile

solution library add nangate-45nm_beh -- -rtlsyntool OasysRTL -vendor Nangate -technology 045nm
solution library add ram_nangate-45nm-singleport_beh
solution library add ram_nangate-45nm-separate_beh
solution library add ram_nangate-45nm-dualport_beh
solution library add ram_nangate-45nm-register-file_beh
go libraries

directive set -CLOCKS {clk {-CLOCK_PERIOD 10 -CLOCK_HIGH_TIME 5 -CLOCK_OFFSET 0.0 -CLOCK_UNCERTAINTY 0.0}}
go assembly

# The IP's directives, GENERATED by Allo from IPModule(sc_directives=...) and
# already re-rooted at this design's top. Previously five hand-copied lines.
source "$HERE/ip_directives.tcl"

go architect
go allocate
go extract

puts "=== CHIP SYNTHESIS COMPLETE"
project save
exit 0
