// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matmul_outer_matmul_outer_Pipeline_l_S_k_0_k (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf0_17,
        buf0_18,
        buf0_19,
        buf0_20,
        buf1_17,
        buf1_21,
        buf1_25,
        buf1_29,
        buf1_18,
        buf1_22,
        buf1_26,
        buf1_30,
        buf1_19,
        buf1_23,
        buf1_27,
        buf1_31,
        buf1_20,
        buf1_24,
        buf1_28,
        buf1_32,
        buf0_21,
        buf0_22,
        buf0_23,
        buf0_24,
        buf0_25,
        buf0_26,
        buf0_27,
        buf0_28,
        buf0_29,
        buf0_30,
        buf0_31,
        buf0_32,
        v33_15_out,
        v33_15_out_ap_vld,
        v33_14_out,
        v33_14_out_ap_vld,
        v33_13_out,
        v33_13_out_ap_vld,
        v33_12_out,
        v33_12_out_ap_vld,
        v33_11_out,
        v33_11_out_ap_vld,
        v33_10_out,
        v33_10_out_ap_vld,
        v33_9_out,
        v33_9_out_ap_vld,
        v33_8_out,
        v33_8_out_ap_vld,
        v33_7_out,
        v33_7_out_ap_vld,
        v33_6_out,
        v33_6_out_ap_vld,
        v33_5_out,
        v33_5_out_ap_vld,
        v33_4_out,
        v33_4_out_ap_vld,
        v33_3_out,
        v33_3_out_ap_vld,
        v33_2_out,
        v33_2_out_ap_vld,
        v33_1_out,
        v33_1_out_ap_vld,
        v33_out,
        v33_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] buf0_17;
input  [31:0] buf0_18;
input  [31:0] buf0_19;
input  [31:0] buf0_20;
input  [31:0] buf1_17;
input  [31:0] buf1_21;
input  [31:0] buf1_25;
input  [31:0] buf1_29;
input  [31:0] buf1_18;
input  [31:0] buf1_22;
input  [31:0] buf1_26;
input  [31:0] buf1_30;
input  [31:0] buf1_19;
input  [31:0] buf1_23;
input  [31:0] buf1_27;
input  [31:0] buf1_31;
input  [31:0] buf1_20;
input  [31:0] buf1_24;
input  [31:0] buf1_28;
input  [31:0] buf1_32;
input  [31:0] buf0_21;
input  [31:0] buf0_22;
input  [31:0] buf0_23;
input  [31:0] buf0_24;
input  [31:0] buf0_25;
input  [31:0] buf0_26;
input  [31:0] buf0_27;
input  [31:0] buf0_28;
input  [31:0] buf0_29;
input  [31:0] buf0_30;
input  [31:0] buf0_31;
input  [31:0] buf0_32;
output  [31:0] v33_15_out;
output   v33_15_out_ap_vld;
output  [31:0] v33_14_out;
output   v33_14_out_ap_vld;
output  [31:0] v33_13_out;
output   v33_13_out_ap_vld;
output  [31:0] v33_12_out;
output   v33_12_out_ap_vld;
output  [31:0] v33_11_out;
output   v33_11_out_ap_vld;
output  [31:0] v33_10_out;
output   v33_10_out_ap_vld;
output  [31:0] v33_9_out;
output   v33_9_out_ap_vld;
output  [31:0] v33_8_out;
output   v33_8_out_ap_vld;
output  [31:0] v33_7_out;
output   v33_7_out_ap_vld;
output  [31:0] v33_6_out;
output   v33_6_out_ap_vld;
output  [31:0] v33_5_out;
output   v33_5_out_ap_vld;
output  [31:0] v33_4_out;
output   v33_4_out_ap_vld;
output  [31:0] v33_3_out;
output   v33_3_out_ap_vld;
output  [31:0] v33_2_out;
output   v33_2_out_ap_vld;
output  [31:0] v33_1_out;
output   v33_1_out_ap_vld;
output  [31:0] v33_out;
output   v33_out_ap_vld;

reg ap_idle;
reg v33_15_out_ap_vld;
reg v33_14_out_ap_vld;
reg v33_13_out_ap_vld;
reg v33_12_out_ap_vld;
reg v33_11_out_ap_vld;
reg v33_10_out_ap_vld;
reg v33_9_out_ap_vld;
reg v33_8_out_ap_vld;
reg v33_7_out_ap_vld;
reg v33_6_out_ap_vld;
reg v33_5_out_ap_vld;
reg v33_4_out_ap_vld;
reg v33_3_out_ap_vld;
reg v33_2_out_ap_vld;
reg v33_1_out_ap_vld;
reg v33_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln96_fu_658_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln96_reg_1278;
reg   [0:0] icmp_ln96_reg_1278_pp0_iter1_reg;
wire  signed [31:0] v25_fu_674_p11;
reg  signed [31:0] v25_reg_1282;
wire  signed [31:0] v29_fu_698_p11;
reg  signed [31:0] v29_reg_1290;
wire  signed [31:0] v29_1_fu_722_p11;
reg  signed [31:0] v29_1_reg_1298;
wire  signed [31:0] v29_2_fu_746_p11;
reg  signed [31:0] v29_2_reg_1306;
wire  signed [31:0] v29_3_fu_770_p11;
reg  signed [31:0] v29_3_reg_1314;
wire  signed [31:0] v25_1_fu_794_p11;
reg  signed [31:0] v25_1_reg_1322;
wire  signed [31:0] v25_2_fu_818_p11;
reg  signed [31:0] v25_2_reg_1330;
wire  signed [31:0] v25_3_fu_842_p11;
reg  signed [31:0] v25_3_reg_1338;
wire   [31:0] grp_fu_506_p2;
reg   [31:0] mul_ln112_reg_1346;
wire   [31:0] grp_fu_510_p2;
reg   [31:0] mul_ln112_1_reg_1351;
wire   [31:0] grp_fu_514_p2;
reg   [31:0] mul_ln112_2_reg_1356;
wire   [31:0] grp_fu_518_p2;
reg   [31:0] mul_ln112_3_reg_1361;
wire   [31:0] grp_fu_522_p2;
reg   [31:0] mul_ln112_4_reg_1366;
wire   [31:0] grp_fu_526_p2;
reg   [31:0] mul_ln112_5_reg_1371;
wire   [31:0] grp_fu_530_p2;
reg   [31:0] mul_ln112_6_reg_1376;
wire   [31:0] grp_fu_534_p2;
reg   [31:0] mul_ln112_7_reg_1381;
wire   [31:0] grp_fu_538_p2;
reg   [31:0] mul_ln112_8_reg_1386;
wire   [31:0] grp_fu_542_p2;
reg   [31:0] mul_ln112_9_reg_1391;
wire   [31:0] grp_fu_546_p2;
reg   [31:0] mul_ln112_10_reg_1396;
wire   [31:0] grp_fu_550_p2;
reg   [31:0] mul_ln112_11_reg_1401;
wire   [31:0] grp_fu_554_p2;
reg   [31:0] mul_ln112_12_reg_1406;
wire   [31:0] grp_fu_558_p2;
reg   [31:0] mul_ln112_13_reg_1411;
wire   [31:0] grp_fu_562_p2;
reg   [31:0] mul_ln112_14_reg_1416;
wire   [31:0] grp_fu_566_p2;
reg   [31:0] mul_ln112_15_reg_1421;
reg   [31:0] v33_fu_134;
wire   [31:0] v37_fu_919_p2;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg   [31:0] v33_1_fu_138;
wire   [31:0] v37_1_fu_924_p2;
reg   [31:0] v33_2_fu_142;
wire   [31:0] v37_2_fu_929_p2;
reg   [31:0] v33_3_fu_146;
wire   [31:0] v37_3_fu_934_p2;
reg   [31:0] v33_4_fu_150;
wire   [31:0] v37_4_fu_939_p2;
reg   [31:0] v33_5_fu_154;
wire   [31:0] v37_5_fu_944_p2;
reg   [31:0] v33_6_fu_158;
wire   [31:0] v37_6_fu_949_p2;
reg   [31:0] v33_7_fu_162;
wire   [31:0] v37_7_fu_954_p2;
reg   [31:0] v33_8_fu_166;
wire   [31:0] v37_8_fu_959_p2;
reg   [31:0] v33_9_fu_170;
wire   [31:0] v37_9_fu_964_p2;
reg   [31:0] v33_10_fu_174;
wire   [31:0] v37_10_fu_969_p2;
reg   [31:0] v33_11_fu_178;
wire   [31:0] v37_11_fu_974_p2;
reg   [31:0] v33_12_fu_182;
wire   [31:0] v37_12_fu_979_p2;
reg   [31:0] v33_13_fu_186;
wire   [31:0] v37_13_fu_984_p2;
reg   [31:0] v33_14_fu_190;
wire   [31:0] v37_14_fu_989_p2;
reg   [31:0] v33_15_fu_194;
wire   [31:0] v37_15_fu_994_p2;
reg   [2:0] k_fu_198;
wire   [2:0] add_ln96_fu_664_p2;
reg   [2:0] ap_sig_allocacmp_k_1;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] v25_fu_674_p9;
wire   [1:0] trunc_ln96_fu_670_p1;
wire   [31:0] v29_fu_698_p9;
wire   [31:0] v29_1_fu_722_p9;
wire   [31:0] v29_2_fu_746_p9;
wire   [31:0] v29_3_fu_770_p9;
wire   [31:0] v25_1_fu_794_p9;
wire   [31:0] v25_2_fu_818_p9;
wire   [31:0] v25_3_fu_842_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [1:0] v25_fu_674_p1;
wire   [1:0] v25_fu_674_p3;
wire  signed [1:0] v25_fu_674_p5;
wire  signed [1:0] v25_fu_674_p7;
wire   [1:0] v29_fu_698_p1;
wire   [1:0] v29_fu_698_p3;
wire  signed [1:0] v29_fu_698_p5;
wire  signed [1:0] v29_fu_698_p7;
wire   [1:0] v29_1_fu_722_p1;
wire   [1:0] v29_1_fu_722_p3;
wire  signed [1:0] v29_1_fu_722_p5;
wire  signed [1:0] v29_1_fu_722_p7;
wire   [1:0] v29_2_fu_746_p1;
wire   [1:0] v29_2_fu_746_p3;
wire  signed [1:0] v29_2_fu_746_p5;
wire  signed [1:0] v29_2_fu_746_p7;
wire   [1:0] v29_3_fu_770_p1;
wire   [1:0] v29_3_fu_770_p3;
wire  signed [1:0] v29_3_fu_770_p5;
wire  signed [1:0] v29_3_fu_770_p7;
wire   [1:0] v25_1_fu_794_p1;
wire   [1:0] v25_1_fu_794_p3;
wire  signed [1:0] v25_1_fu_794_p5;
wire  signed [1:0] v25_1_fu_794_p7;
wire   [1:0] v25_2_fu_818_p1;
wire   [1:0] v25_2_fu_818_p3;
wire  signed [1:0] v25_2_fu_818_p5;
wire  signed [1:0] v25_2_fu_818_p7;
wire   [1:0] v25_3_fu_842_p1;
wire   [1:0] v25_3_fu_842_p3;
wire  signed [1:0] v25_3_fu_842_p5;
wire  signed [1:0] v25_3_fu_842_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 v33_fu_134 = 32'd0;
#0 v33_1_fu_138 = 32'd0;
#0 v33_2_fu_142 = 32'd0;
#0 v33_3_fu_146 = 32'd0;
#0 v33_4_fu_150 = 32'd0;
#0 v33_5_fu_154 = 32'd0;
#0 v33_6_fu_158 = 32'd0;
#0 v33_7_fu_162 = 32'd0;
#0 v33_8_fu_166 = 32'd0;
#0 v33_9_fu_170 = 32'd0;
#0 v33_10_fu_174 = 32'd0;
#0 v33_11_fu_178 = 32'd0;
#0 v33_12_fu_182 = 32'd0;
#0 v33_13_fu_186 = 32'd0;
#0 v33_14_fu_190 = 32'd0;
#0 v33_15_fu_194 = 32'd0;
#0 k_fu_198 = 3'd0;
#0 ap_done_reg = 1'b0;
end

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v29_reg_1290),
    .din1(v25_reg_1282),
    .ce(1'b1),
    .dout(grp_fu_506_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v29_1_reg_1298),
    .din1(v25_reg_1282),
    .ce(1'b1),
    .dout(grp_fu_510_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v29_2_reg_1306),
    .din1(v25_reg_1282),
    .ce(1'b1),
    .dout(grp_fu_514_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v29_3_reg_1314),
    .din1(v25_reg_1282),
    .ce(1'b1),
    .dout(grp_fu_518_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_1_reg_1322),
    .din1(v29_reg_1290),
    .ce(1'b1),
    .dout(grp_fu_522_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_1_reg_1322),
    .din1(v29_1_reg_1298),
    .ce(1'b1),
    .dout(grp_fu_526_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_1_reg_1322),
    .din1(v29_2_reg_1306),
    .ce(1'b1),
    .dout(grp_fu_530_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_1_reg_1322),
    .din1(v29_3_reg_1314),
    .ce(1'b1),
    .dout(grp_fu_534_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_2_reg_1330),
    .din1(v29_reg_1290),
    .ce(1'b1),
    .dout(grp_fu_538_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_2_reg_1330),
    .din1(v29_1_reg_1298),
    .ce(1'b1),
    .dout(grp_fu_542_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_2_reg_1330),
    .din1(v29_2_reg_1306),
    .ce(1'b1),
    .dout(grp_fu_546_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_2_reg_1330),
    .din1(v29_3_reg_1314),
    .ce(1'b1),
    .dout(grp_fu_550_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_3_reg_1338),
    .din1(v29_reg_1290),
    .ce(1'b1),
    .dout(grp_fu_554_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_3_reg_1338),
    .din1(v29_1_reg_1298),
    .ce(1'b1),
    .dout(grp_fu_558_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_3_reg_1338),
    .din1(v29_2_reg_1306),
    .ce(1'b1),
    .dout(grp_fu_562_p2)
);

matmul_outer_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v25_3_reg_1338),
    .din1(v29_3_reg_1314),
    .ce(1'b1),
    .dout(grp_fu_566_p2)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U17(
    .din0(buf0_17),
    .din1(buf0_18),
    .din2(buf0_19),
    .din3(buf0_20),
    .def(v25_fu_674_p9),
    .sel(trunc_ln96_fu_670_p1),
    .dout(v25_fu_674_p11)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U18(
    .din0(buf1_17),
    .din1(buf1_21),
    .din2(buf1_25),
    .din3(buf1_29),
    .def(v29_fu_698_p9),
    .sel(trunc_ln96_fu_670_p1),
    .dout(v29_fu_698_p11)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U19(
    .din0(buf1_18),
    .din1(buf1_22),
    .din2(buf1_26),
    .din3(buf1_30),
    .def(v29_1_fu_722_p9),
    .sel(trunc_ln96_fu_670_p1),
    .dout(v29_1_fu_722_p11)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U20(
    .din0(buf1_19),
    .din1(buf1_23),
    .din2(buf1_27),
    .din3(buf1_31),
    .def(v29_2_fu_746_p9),
    .sel(trunc_ln96_fu_670_p1),
    .dout(v29_2_fu_746_p11)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U21(
    .din0(buf1_20),
    .din1(buf1_24),
    .din2(buf1_28),
    .din3(buf1_32),
    .def(v29_3_fu_770_p9),
    .sel(trunc_ln96_fu_670_p1),
    .dout(v29_3_fu_770_p11)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U22(
    .din0(buf0_21),
    .din1(buf0_22),
    .din2(buf0_23),
    .din3(buf0_24),
    .def(v25_1_fu_794_p9),
    .sel(trunc_ln96_fu_670_p1),
    .dout(v25_1_fu_794_p11)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U23(
    .din0(buf0_25),
    .din1(buf0_26),
    .din2(buf0_27),
    .din3(buf0_28),
    .def(v25_2_fu_818_p9),
    .sel(trunc_ln96_fu_670_p1),
    .dout(v25_2_fu_818_p11)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U24(
    .din0(buf0_29),
    .din1(buf0_30),
    .din2(buf0_31),
    .din3(buf0_32),
    .def(v25_3_fu_842_p9),
    .sel(trunc_ln96_fu_670_p1),
    .dout(v25_3_fu_842_p11)
);

matmul_outer_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln96_fu_658_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_198 <= add_ln96_fu_664_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_198 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_10_fu_174 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_10_fu_174 <= v37_10_fu_969_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_11_fu_178 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_11_fu_178 <= v37_11_fu_974_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_12_fu_182 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_12_fu_182 <= v37_12_fu_979_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_13_fu_186 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_13_fu_186 <= v37_13_fu_984_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_14_fu_190 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_14_fu_190 <= v37_14_fu_989_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_15_fu_194 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_15_fu_194 <= v37_15_fu_994_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_1_fu_138 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_1_fu_138 <= v37_1_fu_924_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_2_fu_142 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_2_fu_142 <= v37_2_fu_929_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_3_fu_146 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_3_fu_146 <= v37_3_fu_934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_4_fu_150 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_4_fu_150 <= v37_4_fu_939_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_5_fu_154 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_5_fu_154 <= v37_5_fu_944_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_6_fu_158 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_6_fu_158 <= v37_6_fu_949_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_7_fu_162 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_7_fu_162 <= v37_7_fu_954_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_8_fu_166 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_8_fu_166 <= v37_8_fu_959_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_9_fu_170 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_9_fu_170 <= v37_9_fu_964_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_fu_134 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            v33_fu_134 <= v37_fu_919_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln96_reg_1278 <= icmp_ln96_fu_658_p2;
        icmp_ln96_reg_1278_pp0_iter1_reg <= icmp_ln96_reg_1278;
        v25_1_reg_1322 <= v25_1_fu_794_p11;
        v25_2_reg_1330 <= v25_2_fu_818_p11;
        v25_3_reg_1338 <= v25_3_fu_842_p11;
        v25_reg_1282 <= v25_fu_674_p11;
        v29_1_reg_1298 <= v29_1_fu_722_p11;
        v29_2_reg_1306 <= v29_2_fu_746_p11;
        v29_3_reg_1314 <= v29_3_fu_770_p11;
        v29_reg_1290 <= v29_fu_698_p11;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        mul_ln112_10_reg_1396 <= grp_fu_546_p2;
        mul_ln112_11_reg_1401 <= grp_fu_550_p2;
        mul_ln112_12_reg_1406 <= grp_fu_554_p2;
        mul_ln112_13_reg_1411 <= grp_fu_558_p2;
        mul_ln112_14_reg_1416 <= grp_fu_562_p2;
        mul_ln112_15_reg_1421 <= grp_fu_566_p2;
        mul_ln112_1_reg_1351 <= grp_fu_510_p2;
        mul_ln112_2_reg_1356 <= grp_fu_514_p2;
        mul_ln112_3_reg_1361 <= grp_fu_518_p2;
        mul_ln112_4_reg_1366 <= grp_fu_522_p2;
        mul_ln112_5_reg_1371 <= grp_fu_526_p2;
        mul_ln112_6_reg_1376 <= grp_fu_530_p2;
        mul_ln112_7_reg_1381 <= grp_fu_534_p2;
        mul_ln112_8_reg_1386 <= grp_fu_538_p2;
        mul_ln112_9_reg_1391 <= grp_fu_542_p2;
        mul_ln112_reg_1346 <= grp_fu_506_p2;
    end
end

always @ (*) begin
    if (((icmp_ln96_fu_658_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_k_1 = k_fu_198;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_10_out_ap_vld = 1'b1;
    end else begin
        v33_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_11_out_ap_vld = 1'b1;
    end else begin
        v33_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_12_out_ap_vld = 1'b1;
    end else begin
        v33_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_13_out_ap_vld = 1'b1;
    end else begin
        v33_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_14_out_ap_vld = 1'b1;
    end else begin
        v33_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_15_out_ap_vld = 1'b1;
    end else begin
        v33_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_1_out_ap_vld = 1'b1;
    end else begin
        v33_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_2_out_ap_vld = 1'b1;
    end else begin
        v33_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_3_out_ap_vld = 1'b1;
    end else begin
        v33_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_4_out_ap_vld = 1'b1;
    end else begin
        v33_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_5_out_ap_vld = 1'b1;
    end else begin
        v33_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_6_out_ap_vld = 1'b1;
    end else begin
        v33_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_7_out_ap_vld = 1'b1;
    end else begin
        v33_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_8_out_ap_vld = 1'b1;
    end else begin
        v33_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_9_out_ap_vld = 1'b1;
    end else begin
        v33_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln96_reg_1278_pp0_iter1_reg == 1'd1))) begin
        v33_out_ap_vld = 1'b1;
    end else begin
        v33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln96_fu_664_p2 = (ap_sig_allocacmp_k_1 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln96_fu_658_p2 = ((ap_sig_allocacmp_k_1 == 3'd4) ? 1'b1 : 1'b0);

assign trunc_ln96_fu_670_p1 = ap_sig_allocacmp_k_1[1:0];

assign v25_1_fu_794_p9 = 'bx;

assign v25_2_fu_818_p9 = 'bx;

assign v25_3_fu_842_p9 = 'bx;

assign v25_fu_674_p9 = 'bx;

assign v29_1_fu_722_p9 = 'bx;

assign v29_2_fu_746_p9 = 'bx;

assign v29_3_fu_770_p9 = 'bx;

assign v29_fu_698_p9 = 'bx;

assign v33_10_out = v33_10_fu_174;

assign v33_11_out = v33_11_fu_178;

assign v33_12_out = v33_12_fu_182;

assign v33_13_out = v33_13_fu_186;

assign v33_14_out = v33_14_fu_190;

assign v33_15_out = v33_15_fu_194;

assign v33_1_out = v33_1_fu_138;

assign v33_2_out = v33_2_fu_142;

assign v33_3_out = v33_3_fu_146;

assign v33_4_out = v33_4_fu_150;

assign v33_5_out = v33_5_fu_154;

assign v33_6_out = v33_6_fu_158;

assign v33_7_out = v33_7_fu_162;

assign v33_8_out = v33_8_fu_166;

assign v33_9_out = v33_9_fu_170;

assign v33_out = v33_fu_134;

assign v37_10_fu_969_p2 = (mul_ln112_10_reg_1396 + v33_10_fu_174);

assign v37_11_fu_974_p2 = (mul_ln112_11_reg_1401 + v33_11_fu_178);

assign v37_12_fu_979_p2 = (mul_ln112_12_reg_1406 + v33_12_fu_182);

assign v37_13_fu_984_p2 = (mul_ln112_13_reg_1411 + v33_13_fu_186);

assign v37_14_fu_989_p2 = (mul_ln112_14_reg_1416 + v33_14_fu_190);

assign v37_15_fu_994_p2 = (mul_ln112_15_reg_1421 + v33_15_fu_194);

assign v37_1_fu_924_p2 = (mul_ln112_1_reg_1351 + v33_1_fu_138);

assign v37_2_fu_929_p2 = (mul_ln112_2_reg_1356 + v33_2_fu_142);

assign v37_3_fu_934_p2 = (mul_ln112_3_reg_1361 + v33_3_fu_146);

assign v37_4_fu_939_p2 = (mul_ln112_4_reg_1366 + v33_4_fu_150);

assign v37_5_fu_944_p2 = (mul_ln112_5_reg_1371 + v33_5_fu_154);

assign v37_6_fu_949_p2 = (mul_ln112_6_reg_1376 + v33_6_fu_158);

assign v37_7_fu_954_p2 = (mul_ln112_7_reg_1381 + v33_7_fu_162);

assign v37_8_fu_959_p2 = (mul_ln112_8_reg_1386 + v33_8_fu_166);

assign v37_9_fu_964_p2 = (mul_ln112_9_reg_1391 + v33_9_fu_170);

assign v37_fu_919_p2 = (mul_ln112_reg_1346 + v33_fu_134);

endmodule //matmul_outer_matmul_outer_Pipeline_l_S_k_0_k
