// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matmul_outer_matmul_outer,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.430900,HLS_SYN_LAT=81,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=8108,HLS_SYN_LUT=5043,HLS_VERSION=2023_2}" *)

module matmul_outer (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_state20 = 28'd524288;
parameter    ap_ST_fsm_state21 = 28'd1048576;
parameter    ap_ST_fsm_state22 = 28'd2097152;
parameter    ap_ST_fsm_pp2_stage0 = 28'd4194304;
parameter    ap_ST_fsm_state25 = 28'd8388608;
parameter    ap_ST_fsm_state26 = 28'd16777216;
parameter    ap_ST_fsm_state27 = 28'd33554432;
parameter    ap_ST_fsm_state28 = 28'd67108864;
parameter    ap_ST_fsm_state29 = 28'd134217728;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] v15;
wire   [63:0] v16;
wire   [63:0] v17;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    gmem0_blk_n_R;
wire    ap_CS_fsm_state10;
reg    gmem1_blk_n_AR;
wire    ap_CS_fsm_state11;
reg    gmem1_blk_n_R;
wire    ap_CS_fsm_state19;
reg    gmem2_blk_n_AW;
wire    ap_CS_fsm_state20;
reg    gmem2_blk_n_W;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage0;
reg    gmem2_blk_n_B;
wire    ap_CS_fsm_state29;
reg   [2:0] add_ln5994_reg_476;
reg   [0:0] icmp_ln6093_reg_487;
reg   [2:0] store_res2_l_192_reg_498;
reg   [2:0] store_res2_l_091_reg_509;
reg   [3:0] indvar_flatten1390_reg_520;
reg   [63:0] v17_read_reg_1341;
reg   [63:0] v16_read_reg_1346;
reg   [63:0] gmem0_addr_reg_1447;
wire   [2:0] load_buf0_l_0_fu_611_p3;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
reg    gmem0_ARVALID;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
reg    gmem0_RREADY;
wire   [31:0] gmem0_RDATA;
wire   [8:0] gmem0_RFIFONUM;
wire    gmem0_BVALID;
wire   [3:0] add_ln27_1_fu_627_p2;
wire   [2:0] load_buf0_l_1_fu_713_p2;
wire   [0:0] icmp_ln28_fu_719_p2;
wire   [2:0] add_ln27_fu_725_p2;
wire   [2:0] load_buf1_l_0_fu_765_p3;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
reg    gmem1_ARVALID;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
reg    gmem1_RREADY;
wire   [31:0] gmem1_RDATA;
wire   [8:0] gmem1_RFIFONUM;
wire    gmem1_BVALID;
wire   [3:0] add_ln43_1_fu_781_p2;
wire   [2:0] load_buf1_l_1_fu_867_p2;
wire   [0:0] icmp_ln44_fu_873_p2;
wire   [2:0] add_ln43_fu_879_p2;
reg   [31:0] v33_15_loc_load_reg_1725;
wire    ap_CS_fsm_state22;
reg   [31:0] v33_14_loc_load_reg_1730;
reg   [31:0] v33_13_loc_load_reg_1735;
reg   [31:0] v33_12_loc_load_reg_1740;
reg   [31:0] v33_11_loc_load_reg_1745;
reg   [31:0] v33_10_loc_load_reg_1750;
reg   [31:0] v33_9_loc_load_reg_1755;
reg   [31:0] v33_8_loc_load_reg_1760;
reg   [31:0] v33_7_loc_load_reg_1765;
reg   [31:0] v33_6_loc_load_reg_1770;
reg   [31:0] v33_5_loc_load_reg_1775;
reg   [31:0] v33_4_loc_load_reg_1780;
reg   [31:0] v33_3_loc_load_reg_1785;
reg   [31:0] v33_2_loc_load_reg_1790;
reg   [31:0] v33_1_loc_load_reg_1795;
reg   [31:0] v33_loc_load_reg_1800;
wire   [2:0] store_res2_l_0_fu_1095_p3;
reg   [2:0] store_res2_l_0_reg_1805;
reg    ap_enable_reg_pp2_iter0;
reg    gmem2_AWVALID;
wire    gmem2_AWREADY;
reg    gmem2_WVALID;
wire    gmem2_WREADY;
wire    gmem2_ARREADY;
wire    gmem2_RVALID;
wire   [31:0] gmem2_RDATA;
wire   [8:0] gmem2_RFIFONUM;
wire    gmem2_BVALID;
reg    gmem2_BREADY;
reg    ap_block_pp2_stage0_11001;
wire   [31:0] v14_fu_1191_p11;
reg   [31:0] v14_reg_1810;
wire   [2:0] store_res2_l_1_fu_1215_p2;
reg   [2:0] store_res2_l_1_reg_1815;
wire   [3:0] add_ln59_1_fu_1221_p2;
reg   [3:0] add_ln59_1_reg_1820;
wire   [0:0] icmp_ln60_fu_1227_p2;
reg   [0:0] icmp_ln60_reg_1825;
wire   [2:0] add_ln59_fu_1233_p2;
reg   [2:0] add_ln59_reg_1830;
wire   [0:0] icmp_ln59_fu_1239_p2;
reg   [0:0] icmp_ln59_reg_1835;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_flush_enable;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_start;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_done;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_idle;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_ready;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_15_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_15_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_14_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_14_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_13_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_13_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_12_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_12_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_11_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_11_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_10_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_10_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_9_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_9_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_8_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_8_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_7_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_7_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_6_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_6_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_5_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_5_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_4_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_4_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_3_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_3_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_2_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_2_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_1_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_1_out_ap_vld;
wire   [31:0] grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_out;
wire    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_out_ap_vld;
reg   [2:0] add_ln2752_reg_366;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln27_fu_731_p2;
reg   [0:0] icmp_ln2851_reg_377;
reg   [2:0] load_buf0_l_150_reg_388;
reg   [2:0] load_buf0_l_017_reg_399;
reg   [3:0] indvar_flatten16_reg_410;
reg   [2:0] add_ln4389_reg_421;
wire    ap_CS_fsm_state18;
wire   [0:0] icmp_ln43_fu_885_p2;
reg   [0:0] icmp_ln4488_reg_432;
reg   [2:0] load_buf1_l_187_reg_443;
reg   [2:0] load_buf1_l_054_reg_454;
reg   [3:0] indvar_flatten653_reg_465;
reg   [2:0] ap_phi_mux_add_ln5994_phi_fu_480_p4;
reg   [0:0] ap_phi_mux_icmp_ln6093_phi_fu_491_p4;
reg   [2:0] ap_phi_mux_store_res2_l_192_phi_fu_502_p4;
reg   [2:0] ap_phi_mux_store_res2_l_091_phi_fu_513_p4;
reg   [3:0] ap_phi_mux_indvar_flatten1390_phi_fu_524_p4;
reg    grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_start_reg;
wire    ap_CS_fsm_state21;
wire  signed [63:0] sext_ln27_fu_593_p1;
wire   [63:0] sext_ln43_fu_746_p1;
wire   [63:0] sext_ln59_fu_1028_p1;
wire    ap_block_pp2_stage0_01001;
reg   [31:0] buf0_1518_fu_116;
wire   [1:0] trunc_ln27_fu_619_p1;
wire   [1:0] trunc_ln28_fu_623_p1;
reg   [31:0] buf0_1420_fu_120;
reg   [31:0] buf0_1322_fu_124;
reg   [31:0] buf0_1224_fu_128;
reg   [31:0] buf0_1126_fu_132;
reg   [31:0] buf0_1028_fu_136;
reg   [31:0] buf0_930_fu_140;
reg   [31:0] buf0_832_fu_144;
reg   [31:0] buf0_734_fu_148;
reg   [31:0] buf0_636_fu_152;
reg   [31:0] buf0_538_fu_156;
reg   [31:0] buf0_440_fu_160;
reg   [31:0] buf0_342_fu_164;
reg   [31:0] buf0_244_fu_168;
reg   [31:0] buf0_146_fu_172;
reg   [31:0] buf048_fu_176;
reg   [31:0] buf1_1555_fu_244;
wire   [1:0] trunc_ln43_fu_773_p1;
wire   [1:0] trunc_ln44_fu_777_p1;
reg   [31:0] buf1_1457_fu_248;
reg   [31:0] buf1_1359_fu_252;
reg   [31:0] buf1_1261_fu_256;
reg   [31:0] buf1_1163_fu_260;
reg   [31:0] buf1_1065_fu_264;
reg   [31:0] buf1_967_fu_268;
reg   [31:0] buf1_869_fu_272;
reg   [31:0] buf1_771_fu_276;
reg   [31:0] buf1_673_fu_280;
reg   [31:0] buf1_575_fu_284;
reg   [31:0] buf1_477_fu_288;
reg   [31:0] buf1_379_fu_292;
reg   [31:0] buf1_281_fu_296;
reg   [31:0] buf1_183_fu_300;
reg   [31:0] buf185_fu_304;
wire   [61:0] trunc_ln27_1_fu_583_p4;
wire   [2:0] select_ln77_fu_603_p3;
wire   [61:0] trunc_ln43_1_fu_737_p4;
wire   [2:0] select_ln82_fu_757_p3;
wire   [61:0] trunc_ln59_1_fu_1019_p4;
wire   [2:0] select_ln59_fu_1087_p3;
wire   [31:0] tmp_fu_1111_p9;
wire   [1:0] trunc_ln60_fu_1107_p1;
wire   [31:0] tmp_1_fu_1131_p9;
wire   [31:0] tmp_2_fu_1151_p9;
wire   [31:0] tmp_3_fu_1171_p9;
wire   [31:0] tmp_fu_1111_p11;
wire   [31:0] tmp_1_fu_1131_p11;
wire   [31:0] tmp_2_fu_1151_p11;
wire   [31:0] tmp_3_fu_1171_p11;
wire   [31:0] v14_fu_1191_p9;
wire   [1:0] v14_fu_1191_p10;
reg   [27:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
wire   [1:0] tmp_fu_1111_p1;
wire   [1:0] tmp_fu_1111_p3;
wire  signed [1:0] tmp_fu_1111_p5;
wire  signed [1:0] tmp_fu_1111_p7;
wire   [1:0] tmp_1_fu_1131_p1;
wire   [1:0] tmp_1_fu_1131_p3;
wire  signed [1:0] tmp_1_fu_1131_p5;
wire  signed [1:0] tmp_1_fu_1131_p7;
wire   [1:0] tmp_2_fu_1151_p1;
wire   [1:0] tmp_2_fu_1151_p3;
wire  signed [1:0] tmp_2_fu_1151_p5;
wire  signed [1:0] tmp_2_fu_1151_p7;
wire   [1:0] tmp_3_fu_1171_p1;
wire   [1:0] tmp_3_fu_1171_p3;
wire  signed [1:0] tmp_3_fu_1171_p5;
wire  signed [1:0] tmp_3_fu_1171_p7;
wire   [1:0] v14_fu_1191_p1;
wire   [1:0] v14_fu_1191_p3;
wire  signed [1:0] v14_fu_1191_p5;
wire  signed [1:0] v14_fu_1191_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_start_reg = 1'b0;
#0 buf0_1518_fu_116 = 32'd0;
#0 buf0_1420_fu_120 = 32'd0;
#0 buf0_1322_fu_124 = 32'd0;
#0 buf0_1224_fu_128 = 32'd0;
#0 buf0_1126_fu_132 = 32'd0;
#0 buf0_1028_fu_136 = 32'd0;
#0 buf0_930_fu_140 = 32'd0;
#0 buf0_832_fu_144 = 32'd0;
#0 buf0_734_fu_148 = 32'd0;
#0 buf0_636_fu_152 = 32'd0;
#0 buf0_538_fu_156 = 32'd0;
#0 buf0_440_fu_160 = 32'd0;
#0 buf0_342_fu_164 = 32'd0;
#0 buf0_244_fu_168 = 32'd0;
#0 buf0_146_fu_172 = 32'd0;
#0 buf048_fu_176 = 32'd0;
#0 buf1_1555_fu_244 = 32'd0;
#0 buf1_1457_fu_248 = 32'd0;
#0 buf1_1359_fu_252 = 32'd0;
#0 buf1_1261_fu_256 = 32'd0;
#0 buf1_1163_fu_260 = 32'd0;
#0 buf1_1065_fu_264 = 32'd0;
#0 buf1_967_fu_268 = 32'd0;
#0 buf1_869_fu_272 = 32'd0;
#0 buf1_771_fu_276 = 32'd0;
#0 buf1_673_fu_280 = 32'd0;
#0 buf1_575_fu_284 = 32'd0;
#0 buf1_477_fu_288 = 32'd0;
#0 buf1_379_fu_292 = 32'd0;
#0 buf1_281_fu_296 = 32'd0;
#0 buf1_183_fu_300 = 32'd0;
#0 buf185_fu_304 = 32'd0;
end

matmul_outer_matmul_outer_Pipeline_l_S_k_0_k grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_start),
    .ap_done(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_done),
    .ap_idle(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_idle),
    .ap_ready(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_ready),
    .buf0_17(buf048_fu_176),
    .buf0_18(buf0_146_fu_172),
    .buf0_19(buf0_244_fu_168),
    .buf0_20(buf0_342_fu_164),
    .buf1_17(buf185_fu_304),
    .buf1_21(buf1_477_fu_288),
    .buf1_25(buf1_869_fu_272),
    .buf1_29(buf1_1261_fu_256),
    .buf1_18(buf1_183_fu_300),
    .buf1_22(buf1_575_fu_284),
    .buf1_26(buf1_967_fu_268),
    .buf1_30(buf1_1359_fu_252),
    .buf1_19(buf1_281_fu_296),
    .buf1_23(buf1_673_fu_280),
    .buf1_27(buf1_1065_fu_264),
    .buf1_31(buf1_1457_fu_248),
    .buf1_20(buf1_379_fu_292),
    .buf1_24(buf1_771_fu_276),
    .buf1_28(buf1_1163_fu_260),
    .buf1_32(buf1_1555_fu_244),
    .buf0_21(buf0_440_fu_160),
    .buf0_22(buf0_538_fu_156),
    .buf0_23(buf0_636_fu_152),
    .buf0_24(buf0_734_fu_148),
    .buf0_25(buf0_832_fu_144),
    .buf0_26(buf0_930_fu_140),
    .buf0_27(buf0_1028_fu_136),
    .buf0_28(buf0_1126_fu_132),
    .buf0_29(buf0_1224_fu_128),
    .buf0_30(buf0_1322_fu_124),
    .buf0_31(buf0_1420_fu_120),
    .buf0_32(buf0_1518_fu_116),
    .v33_15_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_15_out),
    .v33_15_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_15_out_ap_vld),
    .v33_14_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_14_out),
    .v33_14_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_14_out_ap_vld),
    .v33_13_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_13_out),
    .v33_13_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_13_out_ap_vld),
    .v33_12_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_12_out),
    .v33_12_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_12_out_ap_vld),
    .v33_11_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_11_out),
    .v33_11_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_11_out_ap_vld),
    .v33_10_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_10_out),
    .v33_10_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_10_out_ap_vld),
    .v33_9_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_9_out),
    .v33_9_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_9_out_ap_vld),
    .v33_8_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_8_out),
    .v33_8_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_8_out_ap_vld),
    .v33_7_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_7_out),
    .v33_7_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_7_out_ap_vld),
    .v33_6_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_6_out),
    .v33_6_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_6_out_ap_vld),
    .v33_5_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_5_out),
    .v33_5_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_5_out_ap_vld),
    .v33_4_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_4_out),
    .v33_4_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_4_out_ap_vld),
    .v33_3_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_3_out),
    .v33_3_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_3_out_ap_vld),
    .v33_2_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_2_out),
    .v33_2_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_2_out_ap_vld),
    .v33_1_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_1_out),
    .v33_1_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_1_out_ap_vld),
    .v33_out(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_out),
    .v33_out_ap_vld(grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_out_ap_vld)
);

matmul_outer_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .v15(v15),
    .v16(v16),
    .v17(v17)
);

matmul_outer_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(gmem0_addr_reg_1447),
    .I_ARLEN(32'd16),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RFIFONUM(gmem0_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(1'b0)
);

matmul_outer_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem1_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(sext_ln43_fu_746_p1),
    .I_ARLEN(32'd16),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(gmem1_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RFIFONUM(gmem1_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(1'b0)
);

matmul_outer_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem2_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(gmem2_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem2_RDATA),
    .I_RFIFONUM(gmem2_RFIFONUM),
    .I_AWVALID(gmem2_AWVALID),
    .I_AWREADY(gmem2_AWREADY),
    .I_AWADDR(sext_ln59_fu_1028_p1),
    .I_AWLEN(32'd16),
    .I_WVALID(gmem2_WVALID),
    .I_WREADY(gmem2_WREADY),
    .I_WDATA(v14_reg_1810),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem2_BVALID),
    .I_BREADY(gmem2_BREADY)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U75(
    .din0(v33_loc_load_reg_1800),
    .din1(v33_1_loc_load_reg_1795),
    .din2(v33_2_loc_load_reg_1790),
    .din3(v33_3_loc_load_reg_1785),
    .def(tmp_fu_1111_p9),
    .sel(trunc_ln60_fu_1107_p1),
    .dout(tmp_fu_1111_p11)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U76(
    .din0(v33_4_loc_load_reg_1780),
    .din1(v33_5_loc_load_reg_1775),
    .din2(v33_6_loc_load_reg_1770),
    .din3(v33_7_loc_load_reg_1765),
    .def(tmp_1_fu_1131_p9),
    .sel(trunc_ln60_fu_1107_p1),
    .dout(tmp_1_fu_1131_p11)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U77(
    .din0(v33_8_loc_load_reg_1760),
    .din1(v33_9_loc_load_reg_1755),
    .din2(v33_10_loc_load_reg_1750),
    .din3(v33_11_loc_load_reg_1745),
    .def(tmp_2_fu_1151_p9),
    .sel(trunc_ln60_fu_1107_p1),
    .dout(tmp_2_fu_1151_p11)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U78(
    .din0(v33_12_loc_load_reg_1740),
    .din1(v33_13_loc_load_reg_1735),
    .din2(v33_14_loc_load_reg_1730),
    .din3(v33_15_loc_load_reg_1725),
    .def(tmp_3_fu_1171_p9),
    .sel(trunc_ln60_fu_1107_p1),
    .dout(tmp_3_fu_1171_p11)
);

matmul_outer_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U79(
    .din0(tmp_fu_1111_p11),
    .din1(tmp_1_fu_1131_p11),
    .din2(tmp_2_fu_1151_p11),
    .din3(tmp_3_fu_1171_p11),
    .def(v14_fu_1191_p9),
    .sel(v14_fu_1191_p10),
    .dout(v14_fu_1191_p11)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp2_flush_enable)) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state22)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if ((1'b1 == ap_CS_fsm_state22)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_start_reg <= 1'b0;
    end else begin
        if (((gmem2_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
            grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_ready == 1'b1)) begin
            grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_731_p2 == 1'd0) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        add_ln2752_reg_366 <= add_ln27_fu_725_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln2752_reg_366 <= 3'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln43_fu_885_p2 == 1'd0) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        add_ln4389_reg_421 <= add_ln43_fu_879_p2;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        add_ln4389_reg_421 <= 3'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln59_reg_1835 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        add_ln5994_reg_476 <= add_ln59_reg_1830;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        add_ln5994_reg_476 <= 3'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_731_p2 == 1'd0) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        icmp_ln2851_reg_377 <= icmp_ln28_fu_719_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln2851_reg_377 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln43_fu_885_p2 == 1'd0) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        icmp_ln4488_reg_432 <= icmp_ln44_fu_873_p2;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        icmp_ln4488_reg_432 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln59_reg_1835 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln6093_reg_487 <= icmp_ln60_reg_1825;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        icmp_ln6093_reg_487 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln59_reg_1835 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        indvar_flatten1390_reg_520 <= add_ln59_1_reg_1820;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        indvar_flatten1390_reg_520 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_731_p2 == 1'd0) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        indvar_flatten16_reg_410 <= add_ln27_1_fu_627_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        indvar_flatten16_reg_410 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln43_fu_885_p2 == 1'd0) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        indvar_flatten653_reg_465 <= add_ln43_1_fu_781_p2;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        indvar_flatten653_reg_465 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_731_p2 == 1'd0) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        load_buf0_l_017_reg_399 <= load_buf0_l_0_fu_611_p3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        load_buf0_l_017_reg_399 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_731_p2 == 1'd0) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        load_buf0_l_150_reg_388 <= load_buf0_l_1_fu_713_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        load_buf0_l_150_reg_388 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln43_fu_885_p2 == 1'd0) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        load_buf1_l_054_reg_454 <= load_buf1_l_0_fu_765_p3;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        load_buf1_l_054_reg_454 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln43_fu_885_p2 == 1'd0) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        load_buf1_l_187_reg_443 <= load_buf1_l_1_fu_867_p2;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        load_buf1_l_187_reg_443 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln59_reg_1835 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        store_res2_l_091_reg_509 <= store_res2_l_0_reg_1805;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        store_res2_l_091_reg_509 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln59_reg_1835 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        store_res2_l_192_reg_498 <= store_res2_l_1_reg_1815;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        store_res2_l_192_reg_498 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        add_ln59_1_reg_1820 <= add_ln59_1_fu_1221_p2;
        add_ln59_reg_1830 <= add_ln59_fu_1233_p2;
        icmp_ln60_reg_1825 <= icmp_ln60_fu_1227_p2;
        store_res2_l_0_reg_1805 <= store_res2_l_0_fu_1095_p3;
        store_res2_l_1_reg_1815 <= store_res2_l_1_fu_1215_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd0) & (trunc_ln27_fu_619_p1 == 2'd0) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf048_fu_176 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd2) & (trunc_ln27_fu_619_p1 == 2'd2) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_1028_fu_136 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd3) & (trunc_ln27_fu_619_p1 == 2'd2) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_1126_fu_132 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd0) & (trunc_ln27_fu_619_p1 == 2'd3) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_1224_fu_128 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd1) & (trunc_ln27_fu_619_p1 == 2'd3) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_1322_fu_124 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd2) & (trunc_ln27_fu_619_p1 == 2'd3) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_1420_fu_120 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd1) & (trunc_ln27_fu_619_p1 == 2'd0) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_146_fu_172 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd3) & (trunc_ln27_fu_619_p1 == 2'd3) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_1518_fu_116 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd2) & (trunc_ln27_fu_619_p1 == 2'd0) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_244_fu_168 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd3) & (trunc_ln27_fu_619_p1 == 2'd0) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_342_fu_164 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd0) & (trunc_ln27_fu_619_p1 == 2'd1) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_440_fu_160 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd1) & (trunc_ln27_fu_619_p1 == 2'd1) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_538_fu_156 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd2) & (trunc_ln27_fu_619_p1 == 2'd1) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_636_fu_152 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd3) & (trunc_ln27_fu_619_p1 == 2'd1) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_734_fu_148 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd0) & (trunc_ln27_fu_619_p1 == 2'd2) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_832_fu_144 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln28_fu_623_p1 == 2'd1) & (trunc_ln27_fu_619_p1 == 2'd2) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        buf0_930_fu_140 <= gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd0) & (trunc_ln43_fu_773_p1 == 2'd0) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf185_fu_304 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd2) & (trunc_ln43_fu_773_p1 == 2'd2) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_1065_fu_264 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd3) & (trunc_ln43_fu_773_p1 == 2'd2) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_1163_fu_260 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd0) & (trunc_ln43_fu_773_p1 == 2'd3) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_1261_fu_256 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd1) & (trunc_ln43_fu_773_p1 == 2'd3) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_1359_fu_252 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd2) & (trunc_ln43_fu_773_p1 == 2'd3) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_1457_fu_248 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd3) & (trunc_ln43_fu_773_p1 == 2'd3) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_1555_fu_244 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd1) & (trunc_ln43_fu_773_p1 == 2'd0) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_183_fu_300 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd2) & (trunc_ln43_fu_773_p1 == 2'd0) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_281_fu_296 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd3) & (trunc_ln43_fu_773_p1 == 2'd0) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_379_fu_292 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd0) & (trunc_ln43_fu_773_p1 == 2'd1) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_477_fu_288 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd1) & (trunc_ln43_fu_773_p1 == 2'd1) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_575_fu_284 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd2) & (trunc_ln43_fu_773_p1 == 2'd1) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_673_fu_280 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd3) & (trunc_ln43_fu_773_p1 == 2'd1) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_771_fu_276 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd0) & (trunc_ln43_fu_773_p1 == 2'd2) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_869_fu_272 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln44_fu_777_p1 == 2'd1) & (trunc_ln43_fu_773_p1 == 2'd2) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        buf1_967_fu_268 <= gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        gmem0_addr_reg_1447 <= sext_ln27_fu_593_p1;
        v16_read_reg_1346 <= v16;
        v17_read_reg_1341 <= v17;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln59_reg_1835 <= icmp_ln59_fu_1239_p2;
        v14_reg_1810 <= v14_fu_1191_p11;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        v33_10_loc_load_reg_1750 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_10_out;
        v33_11_loc_load_reg_1745 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_11_out;
        v33_12_loc_load_reg_1740 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_12_out;
        v33_13_loc_load_reg_1735 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_13_out;
        v33_14_loc_load_reg_1730 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_14_out;
        v33_15_loc_load_reg_1725 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_15_out;
        v33_1_loc_load_reg_1795 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_1_out;
        v33_2_loc_load_reg_1790 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_2_out;
        v33_3_loc_load_reg_1785 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_3_out;
        v33_4_loc_load_reg_1780 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_4_out;
        v33_5_loc_load_reg_1775 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_5_out;
        v33_6_loc_load_reg_1770 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_6_out;
        v33_7_loc_load_reg_1765 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_7_out;
        v33_8_loc_load_reg_1760 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_8_out;
        v33_9_loc_load_reg_1755 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_9_out;
        v33_loc_load_reg_1800 <= grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_v33_out;
    end
end

always @ (*) begin
    if ((gmem0_RVALID == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem1_ARREADY == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((gmem1_RVALID == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem2_AWREADY == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

always @ (*) begin
    if ((gmem2_BVALID == 1'b0)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln59_fu_1239_p2 == 1'd1) & (1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_condition_pp2_flush_enable = 1'b1;
    end else begin
        ap_condition_pp2_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((gmem2_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln59_reg_1835 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_add_ln5994_phi_fu_480_p4 = add_ln59_reg_1830;
    end else begin
        ap_phi_mux_add_ln5994_phi_fu_480_p4 = add_ln5994_reg_476;
    end
end

always @ (*) begin
    if (((icmp_ln59_reg_1835 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_icmp_ln6093_phi_fu_491_p4 = icmp_ln60_reg_1825;
    end else begin
        ap_phi_mux_icmp_ln6093_phi_fu_491_p4 = icmp_ln6093_reg_487;
    end
end

always @ (*) begin
    if (((icmp_ln59_reg_1835 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_indvar_flatten1390_phi_fu_524_p4 = add_ln59_1_reg_1820;
    end else begin
        ap_phi_mux_indvar_flatten1390_phi_fu_524_p4 = indvar_flatten1390_reg_520;
    end
end

always @ (*) begin
    if (((icmp_ln59_reg_1835 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_store_res2_l_091_phi_fu_513_p4 = store_res2_l_0_reg_1805;
    end else begin
        ap_phi_mux_store_res2_l_091_phi_fu_513_p4 = store_res2_l_091_reg_509;
    end
end

always @ (*) begin
    if (((icmp_ln59_reg_1835 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_store_res2_l_192_phi_fu_502_p4 = store_res2_l_1_reg_1815;
    end else begin
        ap_phi_mux_store_res2_l_192_phi_fu_502_p4 = store_res2_l_192_reg_498;
    end
end

always @ (*) begin
    if (((gmem2_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem0_ARVALID = 1'b1;
    end else begin
        gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        gmem0_RREADY = 1'b1;
    end else begin
        gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        gmem1_ARVALID = 1'b1;
    end else begin
        gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        gmem1_RREADY = 1'b1;
    end else begin
        gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((gmem2_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        gmem2_AWVALID = 1'b1;
    end else begin
        gmem2_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem2_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
        gmem2_BREADY = 1'b1;
    end else begin
        gmem2_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        gmem2_WVALID = 1'b1;
    end else begin
        gmem2_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        gmem2_blk_n_AW = m_axi_gmem2_AWREADY;
    end else begin
        gmem2_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        gmem2_blk_n_B = m_axi_gmem2_BVALID;
    end else begin
        gmem2_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        gmem2_blk_n_W = m_axi_gmem2_WREADY;
    end else begin
        gmem2_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln27_fu_731_p2 == 1'd0) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((icmp_ln27_fu_731_p2 == 1'd1) & (gmem0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln43_fu_885_p2 == 1'd0) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else if (((icmp_ln43_fu_885_p2 == 1'd1) & (gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((gmem2_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((ap_enable_reg_pp2_iter0 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((ap_enable_reg_pp2_iter0 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((gmem2_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln27_1_fu_627_p2 = (indvar_flatten16_reg_410 + 4'd1);

assign add_ln27_fu_725_p2 = (load_buf0_l_0_fu_611_p3 + 3'd1);

assign add_ln43_1_fu_781_p2 = (indvar_flatten653_reg_465 + 4'd1);

assign add_ln43_fu_879_p2 = (load_buf1_l_0_fu_765_p3 + 3'd1);

assign add_ln59_1_fu_1221_p2 = (ap_phi_mux_indvar_flatten1390_phi_fu_524_p4 + 4'd1);

assign add_ln59_fu_1233_p2 = (store_res2_l_0_fu_1095_p3 + 3'd1);

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((gmem2_WREADY == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((gmem2_WREADY == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_start = grp_matmul_outer_Pipeline_l_S_k_0_k_fu_531_ap_start_reg;

assign icmp_ln27_fu_731_p2 = ((indvar_flatten16_reg_410 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_719_p2 = ((load_buf0_l_1_fu_713_p2 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_885_p2 = ((indvar_flatten653_reg_465 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_873_p2 = ((load_buf1_l_1_fu_867_p2 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_1239_p2 = ((ap_phi_mux_indvar_flatten1390_phi_fu_524_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_1227_p2 = ((store_res2_l_1_fu_1215_p2 == 3'd4) ? 1'b1 : 1'b0);

assign load_buf0_l_0_fu_611_p3 = ((icmp_ln2851_reg_377[0:0] == 1'b1) ? add_ln2752_reg_366 : load_buf0_l_017_reg_399);

assign load_buf0_l_1_fu_713_p2 = (select_ln77_fu_603_p3 + 3'd1);

assign load_buf1_l_0_fu_765_p3 = ((icmp_ln4488_reg_432[0:0] == 1'b1) ? add_ln4389_reg_421 : load_buf1_l_054_reg_454);

assign load_buf1_l_1_fu_867_p2 = (select_ln82_fu_757_p3 + 3'd1);

assign select_ln59_fu_1087_p3 = ((ap_phi_mux_icmp_ln6093_phi_fu_491_p4[0:0] == 1'b1) ? 3'd0 : ap_phi_mux_store_res2_l_192_phi_fu_502_p4);

assign select_ln77_fu_603_p3 = ((icmp_ln2851_reg_377[0:0] == 1'b1) ? 3'd0 : load_buf0_l_150_reg_388);

assign select_ln82_fu_757_p3 = ((icmp_ln4488_reg_432[0:0] == 1'b1) ? 3'd0 : load_buf1_l_187_reg_443);

assign sext_ln27_fu_593_p1 = $signed(trunc_ln27_1_fu_583_p4);

assign sext_ln43_fu_746_p1 = $signed(trunc_ln43_1_fu_737_p4);

assign sext_ln59_fu_1028_p1 = $signed(trunc_ln59_1_fu_1019_p4);

assign store_res2_l_0_fu_1095_p3 = ((ap_phi_mux_icmp_ln6093_phi_fu_491_p4[0:0] == 1'b1) ? ap_phi_mux_add_ln5994_phi_fu_480_p4 : ap_phi_mux_store_res2_l_091_phi_fu_513_p4);

assign store_res2_l_1_fu_1215_p2 = (select_ln59_fu_1087_p3 + 3'd1);

assign tmp_1_fu_1131_p9 = 'bx;

assign tmp_2_fu_1151_p9 = 'bx;

assign tmp_3_fu_1171_p9 = 'bx;

assign tmp_fu_1111_p9 = 'bx;

assign trunc_ln27_1_fu_583_p4 = {{v15[63:2]}};

assign trunc_ln27_fu_619_p1 = load_buf0_l_0_fu_611_p3[1:0];

assign trunc_ln28_fu_623_p1 = select_ln77_fu_603_p3[1:0];

assign trunc_ln43_1_fu_737_p4 = {{v16_read_reg_1346[63:2]}};

assign trunc_ln43_fu_773_p1 = load_buf1_l_0_fu_765_p3[1:0];

assign trunc_ln44_fu_777_p1 = select_ln82_fu_757_p3[1:0];

assign trunc_ln59_1_fu_1019_p4 = {{v17_read_reg_1341[63:2]}};

assign trunc_ln60_fu_1107_p1 = select_ln59_fu_1087_p3[1:0];

assign v14_fu_1191_p10 = store_res2_l_0_fu_1095_p3[1:0];

assign v14_fu_1191_p9 = 'bx;

endmodule //matmul_outer
